# Generated by Django 5.1.5 on 2025-02-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_sales', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
