# Generated by Django 5.1.5 on 2025-03-25 09:56

import reports.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_savedreport_delete_salesreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreport',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, encoder=reports.utils.DateTimeEncoder),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='result_data',
            field=models.JSONField(default=dict, encoder=reports.utils.DateTimeEncoder),
        ),
    ]
