# Generated by Django 4.2.13 on 2025-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='unit',
            new_name='measurement_code_a9e960_idx',
            old_name='measurement_code_idx',
        ),
        migrations.RenameIndex(
            model_name='unit',
            new_name='measurement_categor_ceb324_idx',
            old_name='measurement_category_idx',
        ),
        migrations.AlterField(
            model_name='unit',
            name='category',
            field=models.CharField(choices=[('weight', 'Weight'), ('volume', 'Volume'), ('count', 'Count')], help_text='Category of the unit: weight, volume, or count', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(help_text="Short code for the unit, e.g., 'g', 'kg', 'oz', 'lb', 'each'", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(help_text="Full name of the unit, e.g., 'gram', 'kilogram', 'ounce'", max_length=50),
        ),
    ]
