# Generated by Django 4.2.13 on 2025-08-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reporttemplate_archived_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['status', 'started_at'], name='reports_rep_status_dd0810_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['saved_report', 'status'], name='reports_rep_saved_r_28842b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['started_at'], name='reports_rep_started_00a619_idx'),
        ),
    ]
