# Generated by Django 4.2.13 on 2025-10-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('reports', '0003_reportexecution_reports_rep_status_dd0810_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportcache',
            name='reports_rep_report__ad8f34_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportcache',
            name='reports_rep_expires_9e7899_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportexecution',
            name='reports_rep_status_dd0810_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportexecution',
            name='reports_rep_saved_r_28842b_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportexecution',
            name='reports_rep_started_00a619_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedreport',
            name='reports_sav_user_id_2c671c_idx',
        ),
        migrations.RemoveIndex(
            model_name='savedreport',
            name='reports_sav_status_cd354b_idx',
        ),
        migrations.AddField(
            model_name='reportcache',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_caches', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='reportcache',
            name='parameters_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='reportcache',
            index=models.Index(fields=['tenant', 'report_type', 'parameters_hash'], name='reports_rep_tenant__63cd6a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcache',
            index=models.Index(fields=['tenant', 'expires_at'], name='reports_rep_tenant__1b4b0a_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['tenant', 'status', 'started_at'], name='reports_rep_tenant__260278_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['tenant', 'saved_report', 'status'], name='reports_rep_tenant__e45abc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['tenant', 'started_at'], name='reports_rep_tenant__34b8f4_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['tenant', 'name'], name='reports_rep_tenant__9f9eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['tenant', 'report_type'], name='reports_rep_tenant__876879_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['tenant', 'user', 'report_type'], name='reports_sav_tenant__3d01ea_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['tenant', 'status', 'next_run'], name='reports_sav_tenant__2e0574_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcache',
            constraint=models.UniqueConstraint(fields=('tenant', 'parameters_hash'), name='unique_report_cache_per_tenant'),
        ),
    ]
