# Generated by Django 4.2.13 on 2025-10-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_fix_remaining_null_tenants'),  # Wait for data migration
        ('reports', '0004_remove_reportcache_reports_rep_report__ad8f34_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcache',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_caches', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='reportexecution',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='tenant.tenant'),
        ),
    ]
