# Generated by Django 4.2.13 on 2025-10-13 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_alter_reportcache_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportexecution',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='report_type',
            field=models.CharField(blank=True, choices=[('summary', 'Summary Report'), ('sales', 'Sales Report'), ('products', 'Products Report'), ('payments', 'Payments Report'), ('operations', 'Operations Report')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='result_data',
            field=models.JSONField(blank=True, help_text='Generated report data', null=True),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedreport',
            name='last_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.reportexecution'),
        ),
        migrations.AlterField(
            model_name='reportexecution',
            name='saved_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reports.savedreport'),
        ),
    ]
