# Generated by Django 4.2.13 on 2025-06-17 17:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HOLD', 'Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('VOID', 'Void')], default='PENDING', max_length=10)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('order_type', models.CharField(choices=[('POS', 'Point of Sale'), ('WEB', 'Website'), ('APP', 'Customer App'), ('DELIVERY', 'Delivery Platform')], default='POS', max_length=10)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='UNPAID', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_discounts_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('surcharges_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_in_progress', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['order_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent to Kitchen'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup'), ('SERVED', 'Served')], default='PENDING', max_length=10)),
                ('notes', models.TextField(blank=True, help_text="Customer notes, e.g., 'no onions'")),
                ('price_at_sale', models.DecimalField(decimal_places=2, help_text='Price of the product at the time of sale.', max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The calculated discount amount for this specific application.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='discounts.discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_discounts', to='orders.order')),
            ],
        ),
    ]
