# Generated by Django 4.2.13 on 2025-06-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_in_progress',
        ),
    ]
