# Generated by Django 4.2.13 on 2025-06-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
