# Generated by Django 4.2.13 on 2025-06-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_payment_in_progress_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email address for guest orders', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_id',
            field=models.CharField(blank=True, db_index=True, help_text='Session-based identifier for guest users', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_phone',
            field=models.CharField(blank=True, help_text='Phone number for guest orders', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False), ('status', 'PENDING')), fields=('guest_id',), name='unique_guest_pending_order'),
        ),
    ]
