# Generated by Django 4.2.13 on 2025-06-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_guest_email_order_guest_id_order_guest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_first_name',
            field=models.CharField(blank=True, help_text='First name for guest orders', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='guest_last_name',
            field=models.CharField(blank=True, help_text='Last name for guest orders', max_length=150, null=True),
        ),
    ]
