# Generated by Django 4.2.13 on 2025-07-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_guest_first_name_order_guest_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_sent',
            field=models.BooleanField(default=False, help_text='Whether an order confirmation email has been sent for this order'),
        ),
    ]
