# Generated by Django 4.2.13 on 2025-07-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_confirmation_sent_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='surcharges_total',
        ),
    ]
