# Generated by Django 4.2.13 on 2025-07-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_surcharges_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surcharges_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
