# Generated by Django 4.2.13 on 2025-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_created_at_alter_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='kitchen_printed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this item was first sent to kitchen. Prevents duplicate printing.', null=True),
        ),
    ]
