# Generated by Django 4.2.13 on 2025-07-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_kitchen_printed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_set_name', models.CharField(max_length=100)),
                ('option_name', models.CharField(max_length=100)),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_modifiers_snapshot', to='orders.orderitem')),
            ],
        ),
    ]
