# Generated by Django 4.2.13 on 2025-08-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderitem_options_orderitem_item_sequence_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='order_type_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='order_payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='order_customer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['guest_id', 'status'], name='order_guest_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['cashier'], name='order_cashier_idx'),
        ),
    ]
