# Generated by Django 4.2.13 on 2025-08-09 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_order_number_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at', 'order_number'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
