# Generated by Django 4.2.13 on 2025-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_order_options'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='order_stat_idx',
            old_name='order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_pay_stat_idx',
            old_name='order_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_created_idx',
            old_name='order_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_cust_stat_idx',
            old_name='order_customer_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_guest_stat_idx',
            old_name='order_guest_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_num_idx',
            old_name='order_number_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_stat_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'status'], name='order_pay_st_st_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='item_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='item_product_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['status'], name='item_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['kitchen_printed_at'], name='item_kitchen_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['variation_group', 'item_sequence'], name='item_var_seq_idx'),
        ),
    ]
