# Generated by Django 4.2.13 on 2025-08-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_rename_order_status_idx_order_stat_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('POS', 'Point of Sale'), ('WEB', 'Website'), ('APP', 'Customer App'), ('DOORDASH', 'DoorDash'), ('UBER_EATS', 'Uber Eats')], default='POS', max_length=10),
        ),
    ]
