# Generated by Django 4.2.13 on 2025-08-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dining_preference',
            field=models.CharField(choices=[('DINE_IN', 'Dine In'), ('TAKE_OUT', 'Take Out')], default='TAKE_OUT', help_text='Whether the order is for dine-in or take-out', max_length=10),
        ),
    ]
