# Generated by Django 4.2.13 on 2025-09-10 05:54
# Custom migration to handle bigint to uuid conversion for customer_id

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0020_order_dining_preference'),
    ]

    operations = [
        # Step 1: Drop the existing customer field (bigint foreign key to User)
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        # Step 2: Add the new customer field (uuid foreign key to Customer)
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='orders', 
                to='customers.customer'
            ),
        ),
    ]