# Generated by Django 4.2.13 on 2025-09-14 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_name',
            field=models.CharField(blank=True, help_text='Name for custom items (when product is null)', max_length=200),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for custom items (when product is null)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product reference. Null for custom items.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product'),
        ),
    ]
