# Generated by Django 4.2.13 on 2025-10-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('orders', '0022_orderitem_custom_name_orderitem_custom_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_guest_pending_order',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_pay_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_cust_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_guest_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_cashier_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_num_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_stat_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_pay_st_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='item_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='item_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='item_stat_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='item_kitchen_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='item_var_seq_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderdiscount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_discounts', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='orderitemmodifier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_item_modifiers', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status'], name='order_tenant_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'order_type'], name='order_tenant_type_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'payment_status'], name='order_tenant_pay_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'created_at'], name='order_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='order_ten_cust_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'guest_id', 'status'], name='order_ten_guest_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'cashier'], name='order_tenant_cashier_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'order_number'], name='order_tenant_num_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='order_ten_stat_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'payment_status', 'status'], name='order_ten_pay_st_st_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdiscount',
            index=models.Index(fields=['tenant', 'order'], name='orders_orde_tenant__c7cc63_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant', 'order'], name='item_tenant_order_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant', 'product'], name='item_tenant_product_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant', 'status'], name='item_tenant_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['tenant', 'kitchen_printed_at'], name='item_tenant_kitchen_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemmodifier',
            index=models.Index(fields=['tenant', 'order_item'], name='orders_orde_tenant__91c292_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('order_number__isnull', False)), fields=('tenant', 'order_number'), name='unique_order_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False), ('status', 'PENDING')), fields=('tenant', 'guest_id'), name='unique_guest_pending_order_per_tenant'),
        ),
    ]
