# Generated by Django 4.2.13 on 2025-10-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_fix_remaining_null_tenants'),  # Wait for data migration
        ('orders', '0023_remove_order_unique_guest_pending_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='orderdiscount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_discounts', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='orderitemmodifier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_modifiers', to='tenant.tenant'),
        ),
    ]
