# Generated by Django 4.2.13 on 2025-10-23 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0028_add_web_order_defaults_to_global_settings'),
        ('orders', '0025_add_store_location_with_backfill'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_order_number_per_tenant',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_tenant_num_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='store_location',
            field=models.ForeignKey(blank=True, help_text='Store location where this order was placed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='settings.storelocation'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'store_location', 'order_number'], name='order_loc_num_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'store_location', '-created_at'], name='order_loc_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('order_number__isnull', False)), fields=('tenant', 'store_location', 'order_number'), name='unique_order_number_per_location'),
        ),
    ]
