# Generated by Django 4.2.13 on 2025-10-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_per_location_order_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount calculated for this line item at sale time. Used for per-line refund allocation to prevent penny drift. NULL for legacy orders (pre-migration) - refund logic uses deterministic fallback.', max_digits=10, null=True),
        ),
    ]
