# Generated by Django 4.2.13 on 2025-11-10 21:06

from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    """
    Smart backfill: Set completed_at = updated_at for all COMPLETED orders.
    This gives us the best approximation of when orders were actually completed.
    """
    Order = apps.get_model('orders', 'Order')

    # Update all COMPLETED orders to set completed_at = updated_at
    completed_orders = Order.objects.filter(status='COMPLETED')
    count = completed_orders.count()

    if count > 0:
        # Bulk update for performance
        completed_orders.update(completed_at=models.F('updated_at'))
        print(f"✓ Backfilled completed_at for {count} COMPLETED orders")
    else:
        print("✓ No COMPLETED orders to backfill")


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration: Clear completed_at timestamps.
    """
    Order = apps.get_model('orders', 'Order')
    Order.objects.all().update(completed_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_add_tax_amount_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Timestamp when order was marked as COMPLETED. Use this for daily reports and revenue tracking.', null=True),
        ),
        migrations.RunPython(backfill_completed_at, reverse_backfill),
    ]
