# Generated by Django 4.2.13 on 2025-11-15 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant', '0006_tenant_internal_notes_tenant_ownership_type_and_more'),
        ('orders', '0028_add_completed_at_with_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('ONE_OFF_DISCOUNT', 'One-Off Discount'), ('PRICE_OVERRIDE', 'Price Override')], help_text='Type of adjustment', max_length=50)),
                ('discount_type', models.CharField(blank=True, choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], help_text='Type of discount (percentage or fixed amount)', max_length=20, null=True)),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='Discount value (e.g., 15.00 for 15% or $15)', max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before override', max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, help_text='New overridden price', max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Calculated adjustment amount (negative for discounts, positive for increases)', max_digits=10)),
                ('reason', models.TextField(help_text='Reason for this adjustment (for audit trail)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(help_text='User who initiated this adjustment', on_delete=django.db.models.deletion.PROTECT, related_name='applied_adjustments', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved this adjustment (null if no approval needed)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_adjustments', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order this adjustment applies to', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='Specific item (for price overrides). Null for order-level adjustments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='orders.orderitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_adjustments', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Order Adjustment',
                'verbose_name_plural': 'Order Adjustments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'order'], name='orders_orde_tenant__a00657_idx'), models.Index(fields=['tenant', 'order_item'], name='orders_orde_tenant__fef8eb_idx'), models.Index(fields=['tenant', 'adjustment_type'], name='orders_orde_tenant__084c82_idx'), models.Index(fields=['tenant', 'applied_by'], name='orders_orde_tenant__7514c1_idx')],
            },
        ),
    ]
