# Generated by Django 4.2.13 on 2025-11-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_orderadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_adjustments_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total of all order adjustments (one-off discounts, price overrides). Can be positive or negative.', max_digits=10),
        ),
    ]
