# Generated by Django 4.2.13 on 2025-11-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_order_total_adjustments_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('ONE_OFF_DISCOUNT', 'One-Off Discount'), ('PRICE_OVERRIDE', 'Price Override'), ('TAX_EXEMPT', 'Tax Exempt'), ('FEE_EXEMPT', 'Fee Exempt')], help_text='Type of adjustment', max_length=50),
        ),
    ]
