# Generated by Django 4.2.13 on 2025-11-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_orderadjustment_adjustment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_offline_order',
            field=models.BooleanField(db_index=True, default=False, help_text='True if this order was created while the terminal was offline and later synced'),
        ),
        migrations.AddField(
            model_name='order',
            name='offline_created_at',
            field=models.DateTimeField(blank=True, help_text='Original creation timestamp from when the order was created offline', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='offline_terminal_id',
            field=models.CharField(blank=True, help_text='Device ID of the terminal that created this order while offline', max_length=100, null=True),
        ),
    ]
