# Generated by Django 4.2.13 on 2025-11-13 21:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0006_alter_discount_tenant'),
        ('orders', '0028_add_completed_at_with_backfill'),
        ('tenant', '0006_tenant_internal_notes_tenant_ownership_type_and_more'),
        ('settings', '0031_storelocation_manager_approvals_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerApprovalRequest',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active. Inactive records are considered archived/soft-deleted.')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was archived.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('DISCOUNT', 'Discount Application'), ('ORDER_VOID', 'Order Void'), ('REFUND', 'Refund'), ('PRICE_OVERRIDE', 'Price Override'), ('CUSTOM_ADJUSTMENT', 'Custom Adjustment')], help_text='Type of action requiring approval', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Current status of the approval request', max_length=20)),
                ('related_object_label', models.CharField(blank=True, help_text='Human-readable label for related object (for future extensibility)', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Snapshot of action context (amounts, old values, etc.)')),
                ('reason', models.TextField(blank=True, help_text='Why approval is needed (auto-generated or user-provided)')),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold value that triggered the approval requirement', max_digits=10, null=True)),
                ('expires_at', models.DateTimeField(help_text='When this approval request expires if not acted upon')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the request was approved', null=True)),
                ('denied_at', models.DateTimeField(blank=True, help_text='When the request was denied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(blank=True, help_text='Manager who approved or denied the request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('archived_by', models.ForeignKey(blank=True, help_text='User who archived this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('discount', models.ForeignKey(blank=True, help_text='Related discount if action involves discount application', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='discounts.discount')),
                ('initiator', models.ForeignKey(help_text='User who requested the approval (e.g., cashier)', on_delete=django.db.models.deletion.PROTECT, related_name='initiated_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Related order if action involves an order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='Related order item if action involves a specific item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='orders.orderitem')),
                ('store_location', models.ForeignKey(help_text='Store location where approval is requested', on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='settings.storelocation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Manager Approval Request',
                'verbose_name_plural': 'Manager Approval Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'store_location', 'status', 'created_at'], name='approvals_m_tenant__69bab5_idx'), models.Index(fields=['tenant', 'initiator', 'status'], name='approvals_m_tenant__2bb3be_idx'), models.Index(fields=['tenant', 'approver', 'status'], name='approvals_m_tenant__4432db_idx'), models.Index(fields=['status', 'expires_at'], name='approvals_m_status_f8b98a_idx'), models.Index(fields=['tenant', 'action_type', 'status'], name='approvals_m_tenant__189d49_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active. Inactive records are considered archived/soft-deleted.')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was archived.', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Maximum discount percentage allowed without approval (e.g., 15.00 for 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('max_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum refund amount allowed without approval', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_price_override_amount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum price override amount allowed without approval', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_void_order_amount', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Maximum order total that can be voided without approval', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('approval_expiry_minutes', models.PositiveIntegerField(default=30, help_text='Minutes until pending approval request expires', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('allow_self_approval', models.BooleanField(default=False, help_text='Allow manager to approve their own requests (not recommended)')),
                ('purge_after_days', models.PositiveIntegerField(default=90, help_text='Days to keep resolved approval records before purging', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(730)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, help_text='User who archived this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
                ('store_location', models.OneToOneField(help_text='Store location this policy applies to', on_delete=django.db.models.deletion.CASCADE, related_name='approval_policy', to='settings.storelocation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_policies', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Approval Policy',
                'verbose_name_plural': 'Approval Policies',
                'indexes': [models.Index(fields=['tenant', 'store_location'], name='approvals_a_tenant__ed6840_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='approvalpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'store_location'), name='unique_policy_per_store_location'),
        ),
    ]
