# Generated by Django 4.2.13 on 2025-11-15 19:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalpolicy',
            name='max_fixed_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Maximum fixed dollar discount allowed without approval (e.g., $20 off)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='approvalpolicy',
            name='max_price_override_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum price override amount allowed without approval (total difference including quantity)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
