# Generated by Django 4.2.13 on 2025-11-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_approvalpolicy_max_fixed_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalpolicy',
            name='always_require_approval_for',
            field=models.JSONField(blank=True, default=list, help_text='List of action types that always require approval regardless of threshold. Valid values: DISCOUNT, REFUND, PRICE_OVERRIDE, ORDER_VOID'),
        ),
    ]
