# Generated by Django 4.2.13 on 2025-11-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_approvalpolicy_always_require_approval_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerapprovalrequest',
            name='action_type',
            field=models.CharField(choices=[('DISCOUNT', 'Discount Application'), ('ORDER_VOID', 'Order Void'), ('REFUND', 'Refund'), ('PRICE_OVERRIDE', 'Price Override'), ('CUSTOM_ADJUSTMENT', 'Custom Adjustment'), ('TAX_EXEMPT', 'Tax Exemption'), ('FEE_EXEMPT', 'Fee Exemption')], help_text='Type of action requiring approval', max_length=50),
        ),
    ]
