# Generated by Django 4.2.13 on 2025-11-19 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0004_alter_managerapprovalrequest_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvalpolicy',
            name='purge_after_days',
        ),
        migrations.AlterField(
            model_name='approvalpolicy',
            name='approval_expiry_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Minutes until pending approval request expires (hardcoded to 5 minutes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)]),
        ),
    ]
