# Generated by Django 4.2.13 on 2025-06-17 17:03

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product category.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the category.')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Parent category for creating a hierarchy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product type.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the product type.')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the tax, e.g., 'VAT' or 'Sales Tax'.", max_length=50, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax rate in percentage, e.g., 8.25 for 8.25%.', max_digits=5)),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='The selling price of the product.', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is this product available for sale?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('product_type', models.ForeignKey(help_text='The type of product.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.producttype')),
                ('taxes', models.ManyToManyField(blank=True, help_text='Product-specific taxes. General taxes are handled in Orders.', to='products.tax')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
    ]
