# Generated by Django 4.2.13 on 2025-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="track_inventory",
            field=models.BooleanField(
                default=False,
                help_text="Whether to track inventory levels for this product. When enabled, inventory records will be created and stock will be monitored.",
            ),
        ),
    ]
