# Generated by Django 4.2.13 on 2025-06-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_track_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Product barcode for scanning', max_length=50, null=True, unique=True),
        ),
    ]
