# Generated by Django 4.2.13 on 2025-06-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='The processed WebP image.', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
