# Generated by Django 4.2.13 on 2025-06-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_allow_null_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, help_text='The type of product.', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.producttype'),
        ),
    ]
