# Generated by Django 4.2.13 on 2025-07-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='The product ID from the old system.', null=True, unique=True),
        ),
    ]
