# Generated by Django 4.2.13 on 2025-07-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this category and its products are publicly visible on the website.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Whether this product is publicly visible. Note: The parent category must also be public.'),
        ),
    ]
