# Generated by Django 4.2.13 on 2025-07-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_modifieroption_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifieroption',
            name='is_product_specific',
            field=models.BooleanField(default=False, help_text='Whether this option is specific to certain products or available globally.'),
        ),
    ]
