# Generated by Django 4.2.13 on 2025-08-02 19:41

from django.db import migrations, models


def check_and_add_has_modifiers_field(apps, schema_editor):
    """
    Check if has_modifiers field exists, and add it only if it doesn't exist.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='products_product' AND column_name='has_modifiers';
        """)
        
        if not cursor.fetchone():
            # Column doesn't exist, so add it
            cursor.execute("""
                ALTER TABLE products_product 
                ADD COLUMN has_modifiers boolean DEFAULT false NOT NULL;
            """)


def reverse_has_modifiers_field(apps, schema_editor):
    """
    Remove has_modifiers field if it exists.
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='products_product' AND column_name='has_modifiers';
        """)
        
        if cursor.fetchone():
            cursor.execute("ALTER TABLE products_product DROP COLUMN has_modifiers;")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_archived_at_product_archived_by_and_more'),
    ]

    operations = [
        migrations.RunPython(
            check_and_add_has_modifiers_field,
            reverse_has_modifiers_field,
        ),
    ]
