# Generated by Django 4.2.13 on 2025-08-02 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_product_has_modifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='is_active',
            field=models.BooleanField(
                default=True,
                db_index=True,
                help_text='Designates whether this record is active. Inactive records are considered archived/soft-deleted.'
            ),
        ),
        migrations.AddField(
            model_name='producttype',
            name='archived_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='Timestamp when this record was archived.'
            ),
        ),
        migrations.AddField(
            model_name='producttype',
            name='archived_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products_producttype_archived',
                to=settings.AUTH_USER_MODEL,
                help_text='User who archived this record.'
            ),
        ),
    ]