# Generated by Django 4.2.13 on 2025-08-03 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0016_add_category_archiving'),
    ]

    operations = [
        # REMOVED: AddField for has_modifiers - already exists from migration 0014
        migrations.AlterField(
            model_name='producttype',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_public'], name='product_is_public_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['track_inventory'], name='product_track_inventory_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_category_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='product_barcode_idx'),
        ),
    ]
