# Generated by Django 4.2.13 on 2025-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_remove_modifieroption_is_default"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="product_category_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="product_name_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["product_type"], name="products_pr_product_e2f73c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="products_pr_price_9b1a5f_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["created_at"], name="products_pr_created_52f0d7_idx"
            ),
        ),
    ]
