# Generated by Django 4.2.13 on 2025-09-23 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_producttype_policy_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="available_online",
        ),
        migrations.RemoveField(
            model_name="producttype",
            name="available_pos",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Product category. Leave blank for uncategorized products.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="products.category",
            ),
        ),
    ]
