# Generated by Django 4.2.13 on 2025-09-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_remove_producttype_available_online_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producttype",
            name="critical_stock_threshold",
        ),
        migrations.RemoveField(
            model_name="producttype",
            name="low_stock_threshold",
        ),
    ]
