# Generated by Django 4.2.13 on 2025-09-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_threshold_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='exclude_from_discounts',
            field=models.BooleanField(default=False, help_text='Prevent discounts from being applied to this product type.'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='max_quantity_per_item',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum quantity of any individual product per order.', null=True),
        ),
    ]
