# Generated by Django 4.2.13 on 2025-10-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0003_fix_remaining_null_tenants"),  # Wait for data migration
        ("products", "0024_remove_product_product_is_public_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="tenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="modifieroption",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifier_options",
                to="tenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="modifierset",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifier_sets",
                to="tenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="productmodifierset",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_modifier_sets_link",
                to="tenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="productspecificoption",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_specific_options",
                to="tenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_types",
                to="tenant.tenant",
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taxes",
                to="tenant.tenant",
            ),
        ),
    ]
