# Generated by Django 4.2.13 on 2025-10-17 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_product_has_modifiers_alter_category_tenant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The selling price of the product.",
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, message="Price cannot be negative."
                    ),
                    django.core.validators.MaxValueValidator(
                        1000000, message="Price cannot exceed $1,000,000."
                    ),
                ],
            ),
        ),
    ]
