# Generated by Django 4.2.13 on 2025-11-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0026_product_has_modifiers_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="modifierset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tax",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
