# Generated by Django 4.2.13 on 2025-08-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHoursProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Store', help_text='Name to identify this business hours profile', max_length=100)),
                ('timezone', models.CharField(choices=[('America/New_York', 'Eastern Time'), ('America/Chicago', 'Central Time'), ('America/Denver', 'Mountain Time'), ('America/Los_Angeles', 'Pacific Time'), ('America/Phoenix', 'Arizona Time'), ('Pacific/Honolulu', 'Hawaii Time'), ('America/Anchorage', 'Alaska Time')], default='America/New_York', help_text='Timezone for the business location', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this profile is currently active')),
                ('is_default', models.BooleanField(default=False, help_text='Default profile used when no specific profile is specified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Hours Profile',
                'verbose_name_plural': 'Business Hours Profiles',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RegularHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('is_closed', models.BooleanField(default=False, help_text='Is the business closed this day?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_hours', to='business_hours.businesshoursprofile')),
            ],
            options={
                'verbose_name': 'Regular Hours',
                'verbose_name_plural': 'Regular Hours',
                'ordering': ['day_of_week'],
                'unique_together': {('profile', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='SpecialHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for special hours')),
                ('is_closed', models.BooleanField(default=False, help_text='Is the business closed on this date?')),
                ('reason', models.CharField(blank=True, help_text='Reason for special hours (e.g., "Christmas", "Staff Training")', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='business_hours.businesshoursprofile')),
            ],
            options={
                'verbose_name': 'Special Hours',
                'verbose_name_plural': 'Special Hours',
                'ordering': ['date'],
                'unique_together': {('profile', 'date')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(help_text='Opening time for this slot')),
                ('closing_time', models.TimeField(help_text='Closing time for this slot')),
                ('slot_type', models.CharField(choices=[('regular', 'Regular Hours'), ('lunch', 'Lunch Hours'), ('happy_hour', 'Happy Hour'), ('special', 'Special Hours')], default='regular', help_text='Type of time slot', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regular_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='business_hours.regularhours')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['opening_time'],
            },
        ),
        migrations.CreateModel(
            name='SpecialHoursTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(help_text='Opening time for this slot')),
                ('closing_time', models.TimeField(help_text='Closing time for this slot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('special_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_time_slots', to='business_hours.specialhours')),
            ],
            options={
                'verbose_name': 'Special Hours Time Slot',
                'verbose_name_plural': 'Special Hours Time Slots',
                'ordering': ['opening_time'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the holiday', max_length=100)),
                ('month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Month (1-12)')),
                ('day', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], help_text='Day of month (1-31)')),
                ('is_closed', models.BooleanField(default=True, help_text='Is the business closed on this holiday?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='business_hours.businesshoursprofile')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['month', 'day'],
                'unique_together': {('profile', 'month', 'day')},
            },
        ),
    ]
