# Generated by Django 4.2.13 on 2025-10-07 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_fix_remaining_null_tenants'),
        ('business_hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshoursprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours_profiles', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='holiday',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='regularhours',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular_hours', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='specialhours',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='specialhourstimeslot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_hours_time_slots', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='tenant.tenant'),
        ),
    ]
