# Generated by Django 4.2.13 on 2025-10-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_remove_storelocation_settings_st_tenant__94fd00_idx_and_more'),
        ('tenant', '0005_assign_customers_to_default_tenant'),
        ('business_hours', '0003_make_tenant_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesshoursprofile',
            name='store_location',
            field=models.OneToOneField(blank=True, help_text='Store location this business hours profile belongs to. Leave blank for legacy global profiles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours', to='settings.storelocation'),
        ),
        migrations.AlterField(
            model_name='businesshoursprofile',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default profile used when no specific profile is specified (legacy - for profiles not linked to locations)'),
        ),
        migrations.AlterField(
            model_name='businesshoursprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_hours_profiles', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='regularhours',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular_hours', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='specialhours',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='specialhourstimeslot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='special_hours_time_slots', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='tenant.tenant'),
        ),
    ]
