# Generated by Django 4.2.13 on 2025-10-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_hours', '0004_add_store_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshoursprofile',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time (US)'), ('America/Chicago', 'Central Time (US)'), ('America/Denver', 'Mountain Time (US)'), ('America/Los_Angeles', 'Pacific Time (US)'), ('America/Phoenix', 'Arizona Time (US)'), ('Pacific/Honolulu', 'Hawaii Time (US)'), ('America/Anchorage', 'Alaska Time (US)'), ('America/Toronto', 'Eastern Time (Canada)'), ('America/Vancouver', 'Pacific Time (Canada)'), ('America/Edmonton', 'Mountain Time (Canada)'), ('America/Winnipeg', 'Central Time (Canada)'), ('America/Halifax', 'Atlantic Time (Canada)'), ('Europe/London', 'London (GMT/BST)'), ('Europe/Paris', 'Central European Time'), ('Europe/Berlin', 'Central European Time'), ('Europe/Rome', 'Central European Time'), ('Europe/Madrid', 'Central European Time'), ('Europe/Amsterdam', 'Central European Time'), ('Europe/Brussels', 'Central European Time'), ('Europe/Zurich', 'Central European Time'), ('Europe/Vienna', 'Central European Time'), ('Europe/Athens', 'Eastern European Time'), ('Europe/Helsinki', 'Eastern European Time'), ('Europe/Istanbul', 'Turkey Time'), ('Europe/Moscow', 'Moscow Time'), ('Asia/Dubai', 'Gulf Standard Time'), ('Asia/Karachi', 'Pakistan Standard Time'), ('Asia/Kolkata', 'India Standard Time'), ('Asia/Dhaka', 'Bangladesh Time'), ('Asia/Bangkok', 'Indochina Time'), ('Asia/Singapore', 'Singapore Time'), ('Asia/Hong_Kong', 'Hong Kong Time'), ('Asia/Shanghai', 'China Standard Time'), ('Asia/Tokyo', 'Japan Standard Time'), ('Asia/Seoul', 'Korea Standard Time'), ('Australia/Sydney', 'Australian Eastern Time'), ('Australia/Melbourne', 'Australian Eastern Time'), ('Australia/Brisbane', 'Australian Eastern Time'), ('Australia/Perth', 'Australian Western Time'), ('Australia/Adelaide', 'Australian Central Time'), ('Pacific/Auckland', 'New Zealand Time'), ('America/Sao_Paulo', 'Brasilia Time'), ('America/Argentina/Buenos_Aires', 'Argentina Time'), ('Africa/Johannesburg', 'South Africa Time'), ('Africa/Cairo', 'Egypt Time')], default='America/New_York', help_text='Timezone for the business location', max_length=50),
        ),
    ]
