# Generated by Django 4.2.13 on 2025-09-17 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0022_orderitem_custom_name_orderitem_custom_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KDSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_kitchen_zones', models.JSONField(default=list)),
                ('is_priority', models.BooleanField(default=False)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kds_order', to='orders.order')),
            ],
            options={
                'ordering': ['-is_priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KDSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=50)),
                ('terminal_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_activity'],
                'unique_together': {('zone_id', 'terminal_id')},
            },
        ),
        migrations.CreateModel(
            name='KDSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_zone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_priority', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=255, null=True)),
                ('kds_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kds.kdsorder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_items', to='orders.orderitem')),
            ],
            options={
                'ordering': ['-is_priority', 'kds_order__created_at'],
                'indexes': [models.Index(fields=['assigned_zone', 'status'], name='kds_kdsorde_assigne_21c949_idx'), models.Index(fields=['-is_priority'], name='kds_kdsorde_is_prio_e8c463_idx')],
                'unique_together': {('order_item', 'assigned_zone')},
            },
        ),
        migrations.AddIndex(
            model_name='kdsorder',
            index=models.Index(fields=['status'], name='kds_kdsorde_status_5503fe_idx'),
        ),
        migrations.AddIndex(
            model_name='kdsorder',
            index=models.Index(fields=['created_at'], name='kds_kdsorde_created_e8e5c8_idx'),
        ),
        migrations.AddIndex(
            model_name='kdsorder',
            index=models.Index(fields=['-is_priority', 'created_at'], name='kds_kdsorde_is_prio_ba82e7_idx'),
        ),
    ]
