# Generated by Django 4.2.13 on 2025-09-15 20:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0022_orderitem_custom_name_orderitem_custom_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_printer_id', models.CharField(help_text='References existing printer ID from settings app', max_length=100)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('overnight', 'Overnight')], default='morning', max_length=20)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('completed_items', models.PositiveIntegerField(default=0)),
                ('average_prep_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('items_on_time', models.PositiveIntegerField(default=0)),
                ('overdue_items', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'shift'],
                'unique_together': {('zone_printer_id', 'date', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='KDSSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_printer_id', models.CharField(help_text='References existing printer ID from settings app', max_length=100)),
                ('terminal_id', models.CharField(help_text='Unique identifier for the terminal/device', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_orders_per_column', models.PositiveIntegerField(default=10)),
                ('show_customer_names', models.BooleanField(default=True)),
                ('show_order_type', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('zone_printer_id', 'terminal_id')},
            },
        ),
        migrations.CreateModel(
            name='KDSOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_printer_id', models.CharField(help_text='References existing printer ID from settings app', max_length=100)),
                ('kds_status', models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('completed', 'Completed'), ('held', 'Held')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('started_preparing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('held_at', models.DateTimeField(blank=True, null=True)),
                ('kitchen_notes', models.TextField(blank=True)),
                ('is_priority', models.BooleanField(default=False)),
                ('estimated_prep_time', models.PositiveIntegerField(blank=True, help_text='Estimated prep time in minutes', null=True)),
                ('is_addition', models.BooleanField(default=False, help_text='Item added to existing order')),
                ('is_reappeared_completed', models.BooleanField(default=False, help_text='Previously completed item brought back for context')),
                ('original_completion_time', models.DateTimeField(blank=True, help_text='When item was originally completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kds_item', to='orders.orderitem')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='KDSAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zone_printer_id', models.CharField(help_text='References existing printer ID from settings app', max_length=100)),
                ('alert_type', models.CharField(choices=[('overdue', 'Overdue Order'), ('system', 'System Alert')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem')),
            ],
            options={
                'ordering': ['-created_at', '-priority'],
            },
        ),
    ]
