# Generated by Django 4.2.13 on 2025-09-15 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderitem_custom_name_orderitem_custom_price_and_more'),
        ('kds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdsorderitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kds_items', to='orders.orderitem'),
        ),
        migrations.AlterUniqueTogether(
            name='kdsorderitem',
            unique_together={('order_item', 'zone_printer_id')},
        ),
    ]
