# Generated by Django 4.2.13 on 2025-09-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kds', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kdsorder',
            index=models.Index(fields=['status', 'completed_at'], name='kds_kdsorde_status_a840bd_idx'),
        ),
        migrations.AddIndex(
            model_name='kdsorder',
            index=models.Index(fields=['completed_at'], name='kds_kdsorde_complet_21b81d_idx'),
        ),
        migrations.AddIndex(
            model_name='kdsorder',
            index=models.Index(fields=['status', 'created_at'], name='kds_kdsorde_status_08c407_idx'),
        ),
    ]
