# Generated by Django 4.2.13 on 2025-09-16 06:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderitem_custom_name_orderitem_custom_price_and_more'),
        ('kds', '0002_alter_kdsorderitem_order_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QCOrderView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qc_zone_printer_id', models.CharField(help_text='QC zone this view is for', max_length=100)),
                ('qc_status', models.CharField(choices=[('pending', 'Pending Kitchen'), ('ready_for_qc', 'Ready for QC'), ('in_qc', 'In QC Review'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('ready_for_qc_at', models.DateTimeField(blank=True, null=True)),
                ('qc_started_at', models.DateTimeField(blank=True, null=True)),
                ('qc_completed_at', models.DateTimeField(blank=True, null=True)),
                ('qc_notes', models.TextField(blank=True, help_text='QC notes or issues found')),
                ('requires_remake', models.BooleanField(default=False, help_text='QC flagged items for remake')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_views', to='orders.order')),
            ],
            options={
                'ordering': ['ready_for_qc_at', 'created_at'],
                'unique_together': {('order', 'qc_zone_printer_id')},
            },
        ),
    ]
