# Generated by Django 4.2.13 on 2025-10-01 21:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Display name for the tenant (e.g., Joe's Pizza)", max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier used in subdomain (e.g., joespizza → joespizza.ajeen.com)', unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive tenants cannot access the system')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tenants_slug_3181c2_idx'), models.Index(fields=['is_active'], name='tenants_is_acti_ec1713_idx')],
            },
        ),
    ]
