# Generated by Django 4.2.16 on 2025-10-23 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_assign_customers_to_default_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes about this tenant (billing issues, special arrangements, etc.)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ownership_type',
            field=models.CharField(choices=[('system', 'System Owned'), ('customer', 'Customer Owned'), ('demo', 'Demo/Trial')], default='customer', help_text='Determines access level and billing requirements', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_tier',
            field=models.CharField(blank=True, help_text='Phase 2: basic, pro, enterprise, etc. Phase 1: leave null', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Fully qualified domain name (e.g., order.joespizza.com)', max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary domain for this tenant (used in emails, links, etc.)')),
                ('verified', models.BooleanField(default=False, help_text='Whether domain ownership has been verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When domain was verified', null=True)),
                ('verification_method', models.CharField(choices=[('manual', 'Manual Verification'), ('txt', 'DNS TXT Record'), ('cname', 'DNS CNAME Record'), ('meta', 'HTML Meta Tag'), ('file', 'HTML File Upload')], default='manual', help_text='How domain ownership was verified', max_length=20)),
                ('ssl_enabled', models.BooleanField(default=False, help_text='Whether SSL/TLS is provisioned for this domain')),
                ('ssl_provisioned_at', models.DateTimeField(blank=True, help_text='When SSL certificate was provisioned', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this domain (DNS config, special setup, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this domain', on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Custom Domain',
                'verbose_name_plural': 'Custom Domains',
                'db_table': 'custom_domains',
                'ordering': ['-is_primary', 'domain'],
                'indexes': [models.Index(fields=['domain'], name='custom_doma_domain_480397_idx'), models.Index(fields=['tenant', 'verified'], name='custom_doma_tenant__7323fe_idx'), models.Index(fields=['verified', 'is_primary'], name='custom_doma_verifie_44195a_idx')],
            },
        ),
    ]
