# Generated by Django 4.2.13 on 2025-09-10 04:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="Customer's primary email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(help_text="Customer's hashed password", max_length=128)),
                ('first_name', models.CharField(help_text="Customer's first name", max_length=150)),
                ('last_name', models.CharField(help_text="Customer's last name", max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text="Customer's phone number", max_length=20)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('phone', 'Phone Call'), ('none', 'No Contact')], default='email', help_text='Preferred method of communication', max_length=10)),
                ('marketing_opt_in', models.BooleanField(default=False, help_text='Customer opted in to marketing communications')),
                ('newsletter_subscribed', models.BooleanField(default=False, help_text='Subscribed to newsletter')),
                ('birth_date', models.DateField(blank=True, help_text="Customer's birth date", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the customer account is active')),
                ('email_verified', models.BooleanField(default=False, help_text="Whether customer's email is verified")),
                ('phone_verified', models.BooleanField(default=False, help_text="Whether customer's phone is verified")),
                ('last_login', models.DateTimeField(blank=True, help_text='Last time customer logged in', null=True)),
                ('legacy_id', models.PositiveIntegerField(blank=True, help_text='Original User ID before migration', null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers_customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing'), ('both', 'Shipping & Billing')], default='shipping', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('street_address', models.CharField(max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=50)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'db_table': 'customers_customer_address',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_c_phone_n_cabfe1_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['date_joined'], name='customers_c_date_jo_505519_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_login'], name='customers_c_last_lo_ffefb0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['legacy_id'], name='customers_c_legacy__c1d3ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customeraddress',
            unique_together={('customer', 'address_type', 'is_default')},
        ),
    ]
