# Generated by Django 4.2.13 on 2025-09-11 18:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=40, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'db_table': 'customers_password_reset_token',
                'indexes': [models.Index(fields=['token'], name='customers_p_token_605296_idx'), models.Index(fields=['expires_at'], name='customers_p_expires_c14e7c_idx'), models.Index(fields=['customer', 'used_at'], name='customers_p_custome_ca2808_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerEmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=40, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_tokens', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Email Verification Token',
                'verbose_name_plural': 'Email Verification Tokens',
                'db_table': 'customers_email_verification_token',
                'indexes': [models.Index(fields=['token'], name='customers_e_token_ad0593_idx'), models.Index(fields=['expires_at'], name='customers_e_expires_2fd441_idx'), models.Index(fields=['customer', 'used_at'], name='customers_e_custome_f74f71_idx')],
            },
        ),
    ]
