# Generated by Django 4.2.13 on 2025-10-17 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_make_tenant_required'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_c_email_4fdeb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='customeremailverificationtoken',
            name='customers_e_token_ad0593_idx',
        ),
        migrations.RemoveIndex(
            model_name='customeremailverificationtoken',
            name='customers_e_expires_2fd441_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerpasswordresettoken',
            name='customers_p_token_605296_idx',
        ),
        migrations.RemoveIndex(
            model_name='customerpasswordresettoken',
            name='customers_p_expires_c14e7c_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_tenant__0aea56_idx',
            old_name='customers_cu_tenant_email_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_tenant__359dcd_idx',
            old_name='customers_cu_tenant_active_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_tenant__c1a036_idx',
            old_name='customers_cu_tenant_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='customers_c_tenant__793da8_idx',
            old_name='customers_cu_tenant_joined_idx',
        ),
        migrations.RenameIndex(
            model_name='customeraddress',
            new_name='customers_c_tenant__7b3456_idx',
            old_name='customers_ca_tenant_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='customeraddress',
            new_name='customers_c_tenant__b560a8_idx',
            old_name='customers_ca_tenant_default_idx',
        ),
        migrations.RenameIndex(
            model_name='customeremailverificationtoken',
            new_name='customers_e_tenant__ce57dd_idx',
            old_name='customers_ev_tenant_token_idx',
        ),
        migrations.RenameIndex(
            model_name='customeremailverificationtoken',
            new_name='customers_e_tenant__17fade_idx',
            old_name='customers_ev_tenant_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='customeremailverificationtoken',
            new_name='customers_e_tenant__2add15_idx',
            old_name='customers_ev_tenant_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='customerpasswordresettoken',
            new_name='customers_p_tenant__b94c50_idx',
            old_name='customers_pr_tenant_token_idx',
        ),
        migrations.RenameIndex(
            model_name='customerpasswordresettoken',
            new_name='customers_p_tenant__ecf24e_idx',
            old_name='customers_pr_tenant_cust_idx',
        ),
        migrations.RenameIndex(
            model_name='customerpasswordresettoken',
            new_name='customers_p_tenant__f22387_idx',
            old_name='customers_pr_tenant_expires_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text="Customer's primary email address (unique per tenant)", max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
