# Generated by Django 4.2.13 on 2025-06-09 20:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.08'), help_text='The default sales tax rate as a decimal (e.g., 0.08 for 8%).', max_digits=5)),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='A percentage-based surcharge applied to the subtotal (e.g., 0.02 for 2%).', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
