# Generated by Django 4.2.13 on 2025-06-09 20:43

from django.db import migrations


def create_initial_settings(apps, schema_editor):
    """
    Creates the initial GlobalSettings object if one does not already exist.
    This ensures that the application has a default configuration on its first run.
    """
    GlobalSettings = apps.get_model("settings", "GlobalSettings")
    if not GlobalSettings.objects.exists():
        GlobalSettings.objects.create()


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_settings),
    ]
