# Generated by Django 4.2.13 on 2025-06-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Business closing time (used for reporting).', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='currency',
            field=models.CharField(default='USD', help_text='Three-letter currency code (ISO 4217).', max_length=3),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Business opening time (used for reporting).', null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='print_customer_copy',
            field=models.BooleanField(default=True, help_text='Whether to automatically print a customer copy of receipts.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='receipt_footer',
            field=models.TextField(default='Thank you for your business!', help_text='Custom text to appear at the bottom of receipts.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='receipt_header',
            field=models.TextField(blank=True, help_text='Custom text to appear at the top of receipts.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='store_address',
            field=models.TextField(blank=True, help_text='Full business address for receipts.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='store_email',
            field=models.EmailField(blank=True, help_text='Business email address.', max_length=254),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='store_name',
            field=models.CharField(default='', help_text='Business name displayed on receipts and reports.', max_length=255),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='store_phone',
            field=models.CharField(blank=True, help_text='Business phone number.', max_length=20),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='timezone',
            field=models.CharField(default='UTC', help_text="Business timezone (e.g., 'America/New_York').", max_length=50),
        ),
    ]
