# Generated by Django 4.2.13 on 2025-06-19 20:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_globalsettings_closing_time_globalsettings_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='surcharge_percentage',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='A percentage-based surcharge applied to the subtotal (e.g., 0.02 for 2%).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.08'), help_text='The default sales tax rate as a decimal (e.g., 0.08 for 8%).', max_digits=8),
        ),
    ]
