# Generated by Django 4.2.13 on 2025-06-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_create_initial_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='active_terminal_provider',
            field=models.CharField(choices=[('STRIPE_TERMINAL', 'Stripe Terminal'), ('CLOVER_TERMINAL', 'Clover Terminal')], default='STRIPE_TERMINAL', help_text='The currently active payment terminal provider.', max_length=50),
        ),
    ]
