# Generated by Django 4.2.13 on 2025-06-19 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_globalsettings_surcharge_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='print_customer_copy',
        ),
    ]
