# Generated by Django 4.2.13 on 2025-06-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_globalsettings_active_terminal_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSDevice',
            fields=[
                ('device_id', models.CharField(help_text='Unique identifier for the POS device, generated by the client application.', max_length=255, primary_key=True, serialize=False, unique=True)),
                ('reader_id', models.CharField(help_text='The ID of the Stripe Terminal reader assigned to this device (e.g., tmr_...).', max_length=255)),
                ('nickname', models.CharField(blank=True, help_text="An optional friendly name for the POS station (e.g., 'Front Counter').", max_length=100)),
            ],
            options={
                'verbose_name': 'POS Device Pairing',
                'verbose_name_plural': 'POS Device Pairings',
            },
        ),
    ]
