# Generated by Django 4.2.13 on 2025-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_posdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The user-friendly name of the location.', max_length=255)),
                ('stripe_id', models.CharField(help_text='The ID of the location from Stripe (e.g., tml_...).', max_length=255, unique=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default location for transactions.')),
            ],
            options={
                'verbose_name': 'Terminal Location',
                'verbose_name_plural': 'Terminal Locations',
                'ordering': ['name'],
            },
        ),
    ]
