# Generated by Django 4.2.13 on 2025-06-20 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('settings', '0004_remove_globalsettings_print_customer_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='default_inventory_location',
            field=models.ForeignKey(blank=True, help_text='Default location for inventory operations and sales.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='inventory.location'),
        ),
    ]
