# Generated by Django 4.2.13 on 2025-06-30 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_globalsettings_default_inventory_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_printers', models.JSONField(blank=True, default=list, help_text="List of receipt printer configurations (e.g., [{'name': 'Receipt Printer', 'ip': '192.168.1.100'}])")),
                ('kitchen_printers', models.JSONField(blank=True, default=list, help_text="List of kitchen printer configurations (e.g., [{'name': 'Kitchen Printer', 'ip': '192.168.1.101'}])")),
                ('kitchen_zones', models.JSONField(blank=True, default=list, help_text="Kitchen zone configurations with category filters (e.g., [{'name': 'Grill Station', 'printer_name': 'Kitchen Printer', 'category_ids': [1, 2]}])")),
            ],
            options={
                'verbose_name_plural': 'Printer Configuration',
            },
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The internal name for the store location (e.g., 'Main Street Cafe').", max_length=255, unique=True)),
                ('address', models.TextField(blank=True, help_text='The physical address of the store.')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default location for web orders and new terminals?')),
            ],
            options={
                'verbose_name': 'Store Location',
                'verbose_name_plural': 'Store Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TerminalRegistration',
            fields=[
                ('device_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(blank=True, help_text="A friendly name for the device (e.g., 'Front Counter').", max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reader_id', models.CharField(blank=True, help_text='The ID of the Stripe Terminal reader assigned to this device (e.g., tmr_...).', max_length=255)),
                ('store_location', models.ForeignKey(blank=True, help_text='The primary store location this terminal is physically in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.storelocation')),
            ],
            options={
                'verbose_name': 'Terminal Registration',
                'verbose_name_plural': 'Terminal Registrations',
            },
        ),
        migrations.DeleteModel(
            name='POSDevice',
        ),
        migrations.AlterModelOptions(
            name='terminallocation',
            options={'verbose_name': 'Stripe Location Link', 'verbose_name_plural': 'Stripe Location Links'},
        ),
        migrations.RemoveField(
            model_name='terminallocation',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='terminallocation',
            name='name',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='web_order_auto_print_kitchen',
            field=models.BooleanField(default=True, help_text='Automatically print kitchen tickets when web order is completed.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='web_order_auto_print_receipt',
            field=models.BooleanField(default=True, help_text='Automatically print customer receipt when web order is completed.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='web_order_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable real-time notifications for web orders across all terminals.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='web_order_sound_notification',
            field=models.BooleanField(default=True, help_text='Play sound notification when web order is received.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='default_store_location',
            field=models.ForeignKey(blank=True, help_text='Default store location for web orders and single-location setups.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.storelocation'),
        ),
        migrations.AddField(
            model_name='terminallocation',
            name='store_location',
            field=models.OneToOneField(help_text='The primary store this Stripe configuration is for.', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.storelocation'),
        ),
    ]
