# Generated by Django 4.2.13 on 2025-06-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_printerconfiguration_storelocation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': 'Global Settings'},
        ),
        migrations.AlterModelOptions(
            name='storelocation',
            options={},
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='web_order_auto_print_kitchen',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='web_order_auto_print_receipt',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='web_order_notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='web_order_sound_notification',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='enable_web_order_notifications',
            field=models.BooleanField(default=False, help_text='Enable real-time notifications for new web orders.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='web_order_notification_sound',
            field=models.CharField(blank=True, help_text='Sound notification for web orders.', max_length=255),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='receipt_footer',
            field=models.TextField(default='Thank you for your business!', help_text='The footer text that appears on printed receipts.'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='store_name',
            field=models.CharField(default='Ajeen POS', max_length=100),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=0.08, help_text='The sales tax rate as a decimal (e.g., 0.08 for 8%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Is this the default location for inventory deduction?'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
