# Generated by Django 4.2.13 on 2025-06-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_globalsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='web_order_auto_print_kitchen',
            field=models.BooleanField(default=False, help_text='Automatically print kitchen tickets for new web orders.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='web_order_auto_print_receipt',
            field=models.BooleanField(default=False, help_text='Automatically print a receipt for new web orders.'),
        ),
    ]
