# Generated by Django 4.2.13 on 2025-07-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_add_web_order_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webordersettings',
            options={'verbose_name': 'Web Order Settings'},
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='enable_web_order_notifications',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='web_order_auto_print_kitchen',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='web_order_auto_print_receipt',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='web_order_notification_sound',
        ),
        migrations.AddField(
            model_name='webordersettings',
            name='auto_print_kitchen',
            field=models.BooleanField(default=True, help_text='Automatically print kitchen tickets for new web orders.'),
        ),
        migrations.AddField(
            model_name='webordersettings',
            name='auto_print_receipt',
            field=models.BooleanField(default=True, help_text='Automatically print a receipt for new web orders.'),
        ),
        migrations.AddField(
            model_name='webordersettings',
            name='enable_notifications',
            field=models.BooleanField(default=True, help_text='Enable all notifications for new web orders.'),
        ),
        migrations.AddField(
            model_name='webordersettings',
            name='play_notification_sound',
            field=models.BooleanField(default=True, help_text='Play a sound for new web orders.'),
        ),
        migrations.AlterField(
            model_name='webordersettings',
            name='web_receipt_terminals',
            field=models.ManyToManyField(blank=True, help_text='Select terminals that should receive and print web order notifications/receipts.', related_name='web_order_notifications', to='settings.terminalregistration'),
        ),
    ]
