# Generated by Django 4.2.13 on 2025-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_globalsettings_allow_discount_stacking'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='default_expiration_threshold',
            field=models.PositiveIntegerField(default=7, help_text='Default number of days before expiration to warn about expiring stock. Can be overridden per product.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='default_low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Default threshold below which stock is considered low. Can be overridden per product.', max_digits=10),
        ),
    ]
