# Generated by Django 4.2.13 on 2025-08-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0013_storelocation_archived_at_storelocation_archived_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC (Coordinated Universal Time)'), ('America/New_York', 'Eastern Time (US & Canada)'), ('America/Chicago', 'Central Time (US & Canada)'), ('America/Denver', 'Mountain Time (US & Canada)'), ('America/Los_Angeles', 'Pacific Time (US & Canada)'), ('America/Anchorage', 'Alaska Time (US)'), ('Pacific/Honolulu', 'Hawaii Time (US)'), ('America/Halifax', 'Atlantic Time (Canada)'), ('America/St_Johns', 'Newfoundland Time (Canada)'), ('Europe/London', 'Greenwich Mean Time (UK)'), ('Europe/Paris', 'Central European Time'), ('Europe/Berlin', 'Central European Time (Germany)'), ('Australia/Sydney', 'Australian Eastern Time'), ('Asia/Tokyo', 'Japan Standard Time'), ('Asia/Shanghai', 'China Standard Time')], default='UTC', help_text='Business timezone for reports and business hours. This affects how dates are displayed and interpreted in reports.', max_length=50),
        ),
    ]
