# Generated by Django 4.2.13 on 2025-08-30 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0014_alter_globalsettings_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockActionReasonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was archived.', null=True)),
                ('name', models.CharField(help_text="Name of the stock action reason (e.g., 'Damaged Items', 'Inventory Count')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of when this reason should be used')),
                ('category', models.CharField(choices=[('SYSTEM', 'System'), ('MANUAL', 'Manual'), ('TRANSFER', 'Transfer'), ('CORRECTION', 'Correction'), ('INVENTORY', 'Inventory'), ('WASTE', 'Waste'), ('RESTOCK', 'Restock'), ('BULK', 'Bulk'), ('OTHER', 'Other')], default='OTHER', help_text='Category this reason belongs to for reporting and organization', max_length=20)),
                ('is_system_reason', models.BooleanField(default=False, help_text='System reasons are built-in and cannot be modified by users')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive reasons cannot be selected for new stock operations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, help_text='User who archived this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Action Reason',
                'verbose_name_plural': 'Stock Action Reasons',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['is_active', 'category'], name='settings_st_is_acti_9dc4a5_idx'), models.Index(fields=['is_system_reason'], name='settings_st_is_syst_1c254c_idx')],
            },
        ),
    ]
