# Generated by Django 4.2.13 on 2025-10-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('settings', '0015_stockactionreasonconfig'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockactionreasonconfig',
            name='settings_st_is_acti_9dc4a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockactionreasonconfig',
            name='settings_st_is_syst_1c254c_idx',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_settings', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='printerconfiguration',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printer_configuration', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='stockactionreasonconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_action_reason_configs', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_locations', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='terminallocation',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_locations', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminal_registrations', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='webordersettings',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='web_order_settings', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='terminallocation',
            name='stripe_id',
            field=models.CharField(help_text='The ID of the location from Stripe (e.g., tml_...).', max_length=255),
        ),
        migrations.AlterField(
            model_name='terminalregistration',
            name='device_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='stockactionreasonconfig',
            index=models.Index(fields=['tenant', 'is_active', 'category'], name='settings_st_tenant__48e85d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockactionreasonconfig',
            index=models.Index(fields=['tenant', 'is_system_reason'], name='settings_st_tenant__3025b4_idx'),
        ),
        migrations.AddIndex(
            model_name='storelocation',
            index=models.Index(fields=['tenant', 'name'], name='settings_st_tenant__aedea7_idx'),
        ),
        migrations.AddIndex(
            model_name='storelocation',
            index=models.Index(fields=['tenant', 'is_default'], name='settings_st_tenant__94fd00_idx'),
        ),
        migrations.AddIndex(
            model_name='terminallocation',
            index=models.Index(fields=['tenant', 'store_location'], name='settings_te_tenant__9a94c5_idx'),
        ),
        migrations.AddIndex(
            model_name='terminalregistration',
            index=models.Index(fields=['tenant', 'store_location'], name='settings_te_tenant__5f4f80_idx'),
        ),
        migrations.AddConstraint(
            model_name='terminallocation',
            constraint=models.UniqueConstraint(fields=('tenant', 'stripe_id'), name='unique_stripe_id_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='terminalregistration',
            constraint=models.UniqueConstraint(fields=('tenant', 'device_id'), name='unique_device_id_per_tenant'),
        ),
    ]
