# Generated by Django 4.2.13 on 2025-09-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_stockactionreasonconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerconfiguration',
            name='kitchen_zones',
            field=models.JSONField(blank=True, default=list, help_text="Kitchen zone configurations with category filters and QC status (e.g., [{'name': 'Grill Station', 'printer_name': 'Kitchen Printer', 'category_ids': [1, 2], 'is_qc_zone': false}])"),
        ),
    ]
