# Generated by Django 4.2.13 on 2025-09-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0016_alter_printerconfiguration_kitchen_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerconfiguration',
            name='kitchen_zones',
            field=models.JSONField(blank=True, default=list, help_text="Kitchen zone configurations with category filters and zone type (e.g., [{'name': 'Grill Station', 'printer_name': 'Kitchen Printer', 'category_ids': [1, 2], 'zone_type': 'kitchen', 'is_qc_zone': false}]). zone_type: 'kitchen' for item-level workflow, 'qc' for order-level quality control."),
        ),
    ]
