# Generated by Django 4.2.13 on 2025-10-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_fix_remaining_null_tenants'),  # Wait for data migration
        ('settings', '0016_remove_stockactionreasonconfig_settings_st_is_acti_9dc4a5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_settings', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='printerconfiguration',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='printer_configuration', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='stockactionreasonconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_action_reason_configs', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_locations', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='terminallocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_locations', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='terminalregistration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminal_registrations', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='webordersettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_order_settings', to='tenant.tenant'),
        ),
    ]
