# Generated by Django 4.2.13 on 2025-10-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0017_alter_globalsettings_tenant_and_more'),
        ('terminals', '0001_move_terminalregistration_to_terminals'),
    ]

    operations = [
        # Update FK reference from settings.TerminalRegistration -> terminals.TerminalRegistration
        migrations.AlterField(
            model_name='webordersettings',
            name='web_receipt_terminals',
            field=models.ManyToManyField(
                blank=True,
                help_text='Select terminals that should receive and print web order notifications/receipts.',
                related_name='web_order_notifications',
                to='terminals.terminalregistration'
            ),
        ),
        # Remove TerminalRegistration from state (table stays in DB, managed by terminals app now)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='TerminalRegistration',
                ),
            ],
            database_operations=[
                # No database changes - table managed by terminals app
            ],
        ),
    ]
