# Generated by Django 4.2.13 on 2025-10-07 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_fix_remaining_null_tenants'),
        ('settings', '0018_move_terminalregistration_to_terminals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockactionreasonconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this reason belongs to. NULL for global system reasons shared across all tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_action_reason_configs', to='tenant.tenant'),
        ),
    ]
