# Generated by Django 4.2.13 on 2025-10-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0019_alter_stockactionreasonconfig_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Google Place ID for this location (reviews, maps, directions). Set by POS company staff only.', max_length=255),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for distance calculation and map display', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for distance calculation and map display', max_digits=9, null=True),
        ),
    ]
