# Generated by Django 4.2.13 on 2025-10-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0020_storelocation_google_place_id_storelocation_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='storelocation',
            name='settings_st_tenant__94fd00_idx',
        ),
        migrations.RemoveField(
            model_name='storelocation',
            name='is_default',
        ),
        migrations.AddField(
            model_name='storelocation',
            name='accepts_web_orders',
            field=models.BooleanField(default=True, help_text='Whether this location accepts online orders for pickup/delivery'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='address_line1',
            field=models.CharField(blank=True, help_text="Street address (e.g., '123 Main St')", max_length=255),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='country',
            field=models.CharField(default='US', help_text='Two-letter country code (ISO 3166-1 alpha-2)', max_length=2),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='receipt_footer',
            field=models.TextField(blank=True, help_text='Location-specific receipt footer text. If empty, uses global footer.'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='receipt_header',
            field=models.TextField(blank=True, help_text='Location-specific receipt header text. If empty, uses global header.'),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-friendly identifier for this location (e.g., 'downtown', 'airport')", max_length=100),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='state',
            field=models.CharField(blank=True, help_text='State, province, or region', max_length=100),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Location-specific tax rate (e.g., 0.08 for 8%). If null, uses global tax_rate.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC (Coordinated Universal Time)'), ('America/New_York', 'Eastern Time (US & Canada)'), ('America/Chicago', 'Central Time (US & Canada)'), ('America/Denver', 'Mountain Time (US & Canada)'), ('America/Los_Angeles', 'Pacific Time (US & Canada)'), ('America/Anchorage', 'Alaska Time (US)'), ('Pacific/Honolulu', 'Hawaii Time (US)'), ('America/Halifax', 'Atlantic Time (Canada)'), ('America/St_Johns', 'Newfoundland Time (Canada)'), ('Europe/London', 'Greenwich Mean Time (UK)'), ('Europe/Paris', 'Central European Time'), ('Europe/Berlin', 'Central European Time (Germany)'), ('Australia/Sydney', 'Australian Eastern Time'), ('Asia/Tokyo', 'Japan Standard Time'), ('Asia/Shanghai', 'China Standard Time')], default='UTC', help_text='Location-specific timezone (overrides global setting)', max_length=50),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='web_order_lead_time_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minimum lead time for web orders in minutes'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='address',
            field=models.TextField(blank=True, help_text='DEPRECATED: Use structured address fields instead. Kept for backwards compatibility.'),
        ),
        migrations.AddIndex(
            model_name='storelocation',
            index=models.Index(fields=['tenant', 'slug'], name='settings_st_tenant__f97f0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='storelocation',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__isnull', False), models.Q(('slug', ''), _negated=True)), fields=('tenant', 'slug'), name='unique_slug_per_tenant'),
        ),
    ]
