# Generated by Django 4.2.13 on 2025-10-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0021_remove_storelocation_settings_st_tenant__94fd00_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='default_expiration_threshold',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='default_low_stock_threshold',
        ),
        migrations.AddField(
            model_name='storelocation',
            name='expiration_threshold',
            field=models.PositiveIntegerField(default=7, help_text="Default days before expiration to warn for this location's inventory. Used when storage location or individual stock doesn't specify."),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text="Default low stock threshold for this location's inventory. Used when storage location or individual stock doesn't specify."),
        ),
    ]
