# Generated by Django 4.2.13 on 2025-10-16 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_location_store_location'),
        ('settings', '0022_remove_globalsettings_default_expiration_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='default_inventory_location',
            field=models.ForeignKey(blank=True, help_text='Default inventory location for stock operations at this store.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_store_location', to='inventory.location'),
        ),
    ]
