# Generated by Django 4.2.13 on 2025-10-16 17:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0023_storelocation_default_inventory_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='default_inventory_location',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='default_store_location',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='receipt_footer',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='receipt_header',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='store_address',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='store_email',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='store_phone',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='timezone',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='brand_logo',
            field=models.ImageField(blank=True, help_text='Brand logo used across all locations', null=True, upload_to='brand_logos/'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='brand_name',
            field=models.CharField(default='Ajeen POS', help_text="The tenant's brand name (e.g., 'Pizza Palace Inc'). Used for branding, not store names.", max_length=100),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='brand_primary_color',
            field=models.CharField(default='#000000', help_text='Primary brand color in hex format (e.g., #FF5733)', max_length=7),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='brand_receipt_footer',
            field=models.TextField(default='Thank you for your business!', help_text='Default receipt footer template for all locations. Locations can override.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='brand_receipt_header',
            field=models.TextField(blank=True, help_text='Default receipt header template for all locations. Locations can override.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='brand_secondary_color',
            field=models.CharField(default='#FFFFFF', help_text='Secondary brand color in hex format (e.g., #FFFFFF)', max_length=7),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='active_terminal_provider',
            field=models.CharField(choices=[('STRIPE_TERMINAL', 'Stripe Terminal'), ('CLOVER_TERMINAL', 'Clover Terminal')], default='STRIPE_TERMINAL', help_text='The currently active payment terminal provider for all locations.', max_length=50),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='allow_discount_stacking',
            field=models.BooleanField(default=False, help_text='If true, multiple discounts can be applied to a single order. Same rule for all locations.'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='currency',
            field=models.CharField(default='USD', help_text='Three-letter currency code (ISO 4217). Same for all locations within tenant.', max_length=3),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='surcharge_percentage',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Tenant-wide surcharge percentage applied to subtotal (e.g., 0.02 for 2%).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='name',
            field=models.CharField(help_text="Location name (e.g., 'Downtown NYC', 'LAX Airport')", max_length=100),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='receipt_footer',
            field=models.TextField(blank=True, help_text='Custom receipt footer for this location. If blank, uses brand template.'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='receipt_header',
            field=models.TextField(blank=True, help_text='Custom receipt header for this location. If blank, uses brand template.'),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="This location's tax rate (e.g., 0.08 for 8% sales tax). REQUIRED for operations.", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='storelocation',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC (Coordinated Universal Time)'), ('America/New_York', 'Eastern Time (US & Canada)'), ('America/Chicago', 'Central Time (US & Canada)'), ('America/Denver', 'Mountain Time (US & Canada)'), ('America/Los_Angeles', 'Pacific Time (US & Canada)'), ('America/Anchorage', 'Alaska Time (US)'), ('Pacific/Honolulu', 'Hawaii Time (US)'), ('America/Halifax', 'Atlantic Time (Canada)'), ('America/St_Johns', 'Newfoundland Time (Canada)'), ('Europe/London', 'Greenwich Mean Time (UK)'), ('Europe/Paris', 'Central European Time'), ('Europe/Berlin', 'Central European Time (Germany)'), ('Australia/Sydney', 'Australian Eastern Time'), ('Asia/Tokyo', 'Japan Standard Time'), ('Asia/Shanghai', 'China Standard Time')], default='America/Chicago', help_text="This location's timezone. Used for business hours, reports, and timestamps.", max_length=50),
        ),
    ]
