# Generated by Django 4.2.13 on 2025-10-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0003_terminalregistration_id_and_more'),
        ('settings', '0024_remove_globalsettings_closing_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webordersettings',
            name='web_receipt_terminals',
        ),
        migrations.AddField(
            model_name='storelocation',
            name='auto_print_web_kitchen',
            field=models.BooleanField(blank=True, help_text='Location-specific override for auto-printing kitchen tickets. If null, uses tenant default.', null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='auto_print_web_receipt',
            field=models.BooleanField(blank=True, help_text='Location-specific override for auto-printing receipts. If null, uses tenant default.', null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='enable_web_notifications',
            field=models.BooleanField(blank=True, help_text='Location-specific override for web order notifications. If null, uses tenant default.', null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='play_web_notification_sound',
            field=models.BooleanField(blank=True, help_text='Location-specific override for notification sound. If null, uses tenant default.', null=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='web_notification_terminals',
            field=models.ManyToManyField(blank=True, help_text='Terminals at this location that receive web order notifications and auto-print.', related_name='web_notification_locations', to='terminals.terminalregistration'),
        ),
        migrations.AlterField(
            model_name='webordersettings',
            name='auto_print_kitchen',
            field=models.BooleanField(default=True, help_text='Tenant-wide default: Automatically print kitchen tickets for new web orders.'),
        ),
        migrations.AlterField(
            model_name='webordersettings',
            name='auto_print_receipt',
            field=models.BooleanField(default=True, help_text='Tenant-wide default: Automatically print a receipt for new web orders.'),
        ),
        migrations.AlterField(
            model_name='webordersettings',
            name='enable_notifications',
            field=models.BooleanField(default=True, help_text='Tenant-wide default: Enable all notifications for new web orders.'),
        ),
        migrations.AlterField(
            model_name='webordersettings',
            name='play_notification_sound',
            field=models.BooleanField(default=True, help_text='Tenant-wide default: Play a sound for new web orders.'),
        ),
    ]
