# Generated by Django 4.2.13 on 2025-10-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0025_remove_webordersettings_web_receipt_terminals_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webordersettings',
            options={'verbose_name': 'Web Order Settings', 'verbose_name_plural': 'Web Order Settings'},
        ),
    ]
