# Generated by Django 4.2.13 on 2025-10-18 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0026_alter_webordersettings_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebOrderSettings',
        ),
    ]
