# Generated by Django 4.2.13 on 2025-10-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0027_remove_webordersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='default_auto_print_web_kitchen',
            field=models.BooleanField(default=True, help_text='Tenant-wide default for auto-printing kitchen tickets. Locations can override.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='default_auto_print_web_receipt',
            field=models.BooleanField(default=True, help_text='Tenant-wide default for auto-printing receipts. Locations can override.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='default_enable_web_notifications',
            field=models.BooleanField(default=True, help_text='Tenant-wide default for web order notifications. Locations can override.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='default_play_web_notification_sound',
            field=models.BooleanField(default=True, help_text='Tenant-wide default for notification sound. Locations can override.'),
        ),
    ]
