# Generated by Django 4.2.16 on 2025-10-24 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_tenant_internal_notes_tenant_ownership_type_and_more'),
        ('settings', '0028_add_web_order_defaults_to_global_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Front Counter Receipt Printer')", max_length=100)),
                ('printer_type', models.CharField(choices=[('receipt', 'Receipt Printer'), ('kitchen', 'Kitchen Printer')], help_text='Type of printer: receipt or kitchen', max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the network printer')),
                ('port', models.IntegerField(default=9100, help_text='Port number for printer communication')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this printer is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Store location where this printer is installed', on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='settings.storelocation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'ordering': ['location', 'printer_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KitchenZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for this kitchen zone (e.g., 'Grill Station', 'Bakery')", max_length=100)),
                ('print_all_items', models.BooleanField(default=False, help_text='If true, print all order items regardless of category/type filters')),
                ('auto_print', models.BooleanField(default=True, help_text="Automatically print orders containing items from this zone's categories")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this kitchen zone is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Product categories that should print to this kitchen zone', related_name='kitchen_zones', to='products.category')),
                ('location', models.ForeignKey(help_text='Store location where this kitchen zone is configured', on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_zones', to='settings.storelocation')),
                ('printer', models.ForeignKey(help_text='Kitchen printer assigned to this zone', limit_choices_to={'printer_type': 'kitchen'}, on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_zones', to='settings.printer')),
                ('product_types', models.ManyToManyField(blank=True, help_text='Product types that should print to this kitchen zone', related_name='kitchen_zones', to='products.producttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant')),
            ],
            options={
                'ordering': ['location', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['tenant', 'location', 'is_active'], name='settings_pr_tenant__beb1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='printer',
            index=models.Index(fields=['tenant', 'printer_type'], name='settings_pr_tenant__f31e5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='printer',
            unique_together={('location', 'name')},
        ),
        migrations.AddIndex(
            model_name='kitchenzone',
            index=models.Index(fields=['tenant', 'location', 'is_active'], name='settings_ki_tenant__b41c54_idx'),
        ),
        migrations.AddIndex(
            model_name='kitchenzone',
            index=models.Index(fields=['printer', 'is_active'], name='settings_ki_printer_63224c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kitchenzone',
            unique_together={('location', 'name')},
        ),
    ]
