# Generated by Django 4.2.16 on 2025-10-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0029_add_printer_kitchen_zone_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenzone',
            name='auto_print',
        ),
        migrations.RemoveField(
            model_name='kitchenzone',
            name='product_types',
        ),
        migrations.AlterField(
            model_name='kitchenzone',
            name='print_all_items',
            field=models.BooleanField(default=False, help_text='If true, print all order items regardless of category filters'),
        ),
    ]
