# Generated by Django 4.2.13 on 2025-11-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_remove_kitchenzone_auto_print_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelocation',
            name='manager_approvals_enabled',
            field=models.BooleanField(default=False, help_text='Enable manager approval workflows for sensitive operations (discounts, voids, refunds)'),
        ),
    ]
