# Generated by Django 4.2.13 on 2025-11-21 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_storelocation_manager_approvals_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storelocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storelocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
