# Generated by Django 4.2.13 on 2025-07-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystock',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Date when this stock expires.', null=True),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='expiration_threshold',
            field=models.PositiveIntegerField(default=7, help_text='Number of days before expiration to warn about expiring stock.'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Threshold below which stock is considered low.', max_digits=10),
        ),
    ]
