# Generated by Django 4.2.13 on 2025-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorystock_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='expiration_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days before expiration to warn about expiring stock. If not set, uses global default.', null=True),
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Threshold below which stock is considered low. If not set, uses global default.', max_digits=10, null=True),
        ),
    ]
