# Generated by Django 4.2.13 on 2025-07-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventorystock_expiration_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystock',
            name='low_stock_notified',
            field=models.BooleanField(default=False, help_text='Whether a low stock notification has been sent for this item.'),
        ),
    ]
