# Generated by Django 4.2.13 on 2025-07-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorystock_low_stock_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='expiration_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Default number of days before expiration to warn about expiring stock for this location. If not set, uses global default.', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default low stock threshold for this location. If not set, uses global default.', max_digits=10, null=True),
        ),
    ]
