# Generated by Django 4.2.13 on 2025-08-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorystock_archived_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['product', 'location'], name='inventory_product_location_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['quantity'], name='inventory_quantity_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['expiration_date'], name='inventory_expiration_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['location'], name='inventory_location_idx'),
        ),
    ]
