# Generated by Django 4.2.13 on 2025-08-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorystock_inventory_product_location_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['menu_item'], name='inventory_r_menu_it_753827_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['recipe', 'product'], name='inventory_r_recipe__8e4663_idx'),
        ),
    ]
