# Generated by Django 4.2.13 on 2025-08-21 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0008_recipe_inventory_r_menu_it_753827_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('CREATED', 'Stock Created'), ('ADJUSTED_ADD', 'Stock Added'), ('ADJUSTED_SUBTRACT', 'Stock Subtracted'), ('TRANSFER_FROM', 'Transfer Out'), ('TRANSFER_TO', 'Transfer In'), ('ORDER_DEDUCTION', 'Order Deduction'), ('BULK_ADJUSTMENT', 'Bulk Adjustment'), ('BULK_TRANSFER', 'Bulk Transfer')], help_text='Type of stock operation performed', max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, help_text='Change in quantity (positive for additions, negative for subtractions)', max_digits=10)),
                ('previous_quantity', models.DecimalField(decimal_places=2, help_text='Quantity before the operation', max_digits=10)),
                ('new_quantity', models.DecimalField(decimal_places=2, help_text='Quantity after the operation', max_digits=10)),
                ('reason', models.CharField(blank=True, help_text='Reason for the stock operation', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the operation')),
                ('reference_id', models.CharField(blank=True, help_text='Reference ID to link related operations (e.g., transfer operations, bulk operations)', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the operation was performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where the operation was initiated', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent information')),
                ('location', models.ForeignKey(help_text='Location where the stock operation occurred', on_delete=django.db.models.deletion.PROTECT, related_name='stock_history', to='inventory.location')),
                ('product', models.ForeignKey(help_text='Product involved in the stock operation', on_delete=django.db.models.deletion.PROTECT, related_name='stock_history', to='products.product')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock History Entry',
                'verbose_name_plural': 'Stock History Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product', 'timestamp'], name='stock_hist_prod_time_idx'), models.Index(fields=['location', 'timestamp'], name='stock_hist_loc_time_idx'), models.Index(fields=['user', 'timestamp'], name='stock_hist_user_time_idx'), models.Index(fields=['operation_type'], name='stock_hist_operation_idx'), models.Index(fields=['timestamp'], name='stock_hist_timestamp_idx'), models.Index(fields=['reference_id'], name='stock_hist_reference_idx')],
            },
        ),
    ]
