# Generated by Django 4.2.13 on 2025-08-30 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0015_stockactionreasonconfig'),
        ('inventory', '0009_stockhistoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistoryentry',
            name='detailed_reason',
            field=models.TextField(blank=True, help_text='Optional detailed explanation for the stock operation'),
        ),
        migrations.AddField(
            model_name='stockhistoryentry',
            name='reason_config',
            field=models.ForeignKey(blank=True, help_text='Structured reason for the stock operation', null=True, on_delete=django.db.models.deletion.PROTECT, to='settings.stockactionreasonconfig'),
        ),
        migrations.AlterField(
            model_name='stockhistoryentry',
            name='reason',
            field=models.CharField(blank=True, help_text='Legacy reason for the stock operation (will be migrated)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='stockhistoryentry',
            index=models.Index(fields=['reason_config'], name='stock_hist_reason_idx'),
        ),
    ]
