# Generated by Django 4.2.13 on 2025-10-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('inventory', '0010_stockhistoryentry_detailed_reason_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inventorystock',
            name='inventory_product_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorystock',
            name='inventory_quantity_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorystock',
            name='inventory_expiration_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorystock',
            name='inventory_location_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='inventory_r_menu_it_753827_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipeitem',
            name='inventory_r_recipe__8e4663_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockhistoryentry',
            name='stock_hist_prod_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockhistoryentry',
            name='stock_hist_loc_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockhistoryentry',
            name='stock_hist_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockhistoryentry',
            name='stock_hist_operation_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockhistoryentry',
            name='stock_hist_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockhistoryentry',
            name='stock_hist_reference_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockhistoryentry',
            name='stock_hist_reason_idx',
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stocks', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locations', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='recipeitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='stockhistoryentry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_history_entries', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text='Name of the inventory location.', max_length=100),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['tenant', 'product', 'location'], name='inventory_tenant_prod_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['tenant', 'quantity'], name='inventory_tenant_qty_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['tenant', 'expiration_date'], name='inventory_tenant_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['tenant', 'name'], name='inventory_l_tenant__b46641_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['tenant', 'menu_item'], name='inventory_r_tenant__fa4afe_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeitem',
            index=models.Index(fields=['tenant', 'recipe', 'product'], name='inventory_r_tenant__fc5fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistoryentry',
            index=models.Index(fields=['tenant', 'product', 'timestamp'], name='stock_hist_ten_prod_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistoryentry',
            index=models.Index(fields=['tenant', 'location', 'timestamp'], name='stock_hist_ten_loc_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistoryentry',
            index=models.Index(fields=['tenant', 'user', 'timestamp'], name='stock_hist_ten_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistoryentry',
            index=models.Index(fields=['tenant', 'operation_type'], name='stock_hist_ten_operation_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistoryentry',
            index=models.Index(fields=['tenant', 'timestamp'], name='stock_hist_ten_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistoryentry',
            index=models.Index(fields=['tenant', 'reference_id'], name='stock_hist_ten_reference_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_location_name_per_tenant'),
        ),
    ]
