# Generated by Django 4.2.13 on 2025-10-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_fix_remaining_null_tenants'),  # Wait for data migration
        ('inventory', '0011_remove_inventorystock_inventory_product_location_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stocks', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_locations', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='stockhistoryentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history_entries', to='tenant.tenant'),
        ),
    ]
