# Generated by Django 4.2.13 on 2025-10-16 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_remove_globalsettings_default_expiration_threshold_and_more'),
        ('inventory', '0012_alter_inventorystock_tenant_alter_location_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='store_location',
            field=models.ForeignKey(blank=True, help_text='The store this storage location belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_locations', to='settings.storelocation'),
        ),
    ]
