# Generated by Django 4.2.13 on 2025-11-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0031_storelocation_manager_approvals_enabled'),
        ('inventory', '0014_backfill_and_require_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='store_location',
            field=models.ForeignKey(blank=True, help_text='Denormalized from location.store_location for fast queries', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_stocks', to='settings.storelocation'),
        ),
        migrations.AlterField(
            model_name='location',
            name='store_location',
            field=models.ForeignKey(blank=True, help_text='The store this storage location belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_locations', to='settings.storelocation'),
        ),
        migrations.AlterField(
            model_name='stockhistoryentry',
            name='store_location',
            field=models.ForeignKey(blank=True, help_text='Denormalized from location.store_location for fast audit queries', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_history_entries', to='settings.storelocation'),
        ),
    ]
