# Generated by Django 4.2.13 on 2025-11-21 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0006_tenant_internal_notes_tenant_ownership_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terminals', '0004_terminalregistration_offline_capture_window_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('PRODUCT_DELETED', 'Product Deleted'), ('PRODUCT_PRICE_CHANGED', 'Price Changed'), ('INSUFFICIENT_STOCK', 'Insufficient Stock'), ('DATASET_VERSION_MISMATCH', 'Dataset Version Mismatch'), ('INVALID_SIGNATURE', 'Invalid Signature'), ('REPLAY_ATTACK', 'Replay Attack Detected'), ('LIMIT_EXCEEDED', 'Offline Limit Exceeded'), ('OTHER', 'Other')], help_text='Type of conflict encountered', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Resolution'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], default='PENDING', help_text='Current resolution status', max_length=20)),
                ('operation_id', models.UUIDField(help_text='Client-generated operation ID from payload')),
                ('payload_snapshot', models.JSONField(help_text='Snapshot of the conflicting payload for debugging')),
                ('conflict_message', models.TextField(help_text='Human-readable description of the conflict')),
                ('affected_entity_type', models.CharField(blank=True, help_text="Entity type involved (e.g., 'product', 'order', 'inventory')", max_length=50)),
                ('affected_entity_id', models.CharField(blank=True, help_text='ID of the affected entity', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the conflict was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the conflict was resolved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved this conflict', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_conflicts', to='tenant.tenant')),
                ('terminal', models.ForeignKey(help_text='Terminal that submitted the conflicting payload', on_delete=django.db.models.deletion.CASCADE, related_name='offline_conflicts', to='terminals.terminalregistration')),
            ],
            options={
                'verbose_name': 'Offline Conflict',
                'verbose_name_plural': 'Offline Conflicts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(db_index=True, help_text='Client-generated operation ID from the payload')),
                ('operation_type', models.CharField(choices=[('OFFLINE_ORDER', 'Offline Order'), ('OFFLINE_INVENTORY', 'Offline Inventory'), ('OFFLINE_APPROVALS', 'Offline Approvals')], help_text='Type of operation that was processed', max_length=50)),
                ('result_data', models.JSONField(help_text='Response that was returned to the client')),
                ('order_id', models.UUIDField(blank=True, help_text='Order ID if this was an order operation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this idempotency record expires (30 days)')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_operations', to='tenant.tenant')),
                ('terminal', models.ForeignKey(help_text='Terminal that submitted this operation', on_delete=django.db.models.deletion.CASCADE, related_name='processed_operations', to='terminals.terminalregistration')),
            ],
            options={
                'verbose_name': 'Processed Operation',
                'verbose_name_plural': 'Processed Operations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'operation_id'], name='sync_proces_tenant__d6c6ea_idx'), models.Index(fields=['terminal', 'operation_id'], name='sync_proces_termina_ba6c5a_idx'), models.Index(fields=['expires_at'], name='sync_proces_expires_259234_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='processedoperation',
            constraint=models.UniqueConstraint(fields=('tenant', 'terminal', 'operation_id'), name='unique_operation_per_terminal'),
        ),
        migrations.AddIndex(
            model_name='offlineconflict',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='sync_offlin_tenant__a9db51_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineconflict',
            index=models.Index(fields=['tenant', 'terminal', 'status'], name='sync_offlin_tenant__4804d3_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineconflict',
            index=models.Index(fields=['tenant', 'conflict_type'], name='sync_offlin_tenant__b37f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='offlineconflict',
            index=models.Index(fields=['operation_id'], name='sync_offlin_operati_6edb43_idx'),
        ),
    ]
