# Generated by Django 4.2.13 on 2025-06-12 22:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The tip amount for this payment.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('PENDING', 'Pending')], default='PENDING', help_text='The current status of the payment.', max_length=20),
        ),
    ]
