# Generated by Django 4.2.13 on 2025-06-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='card_brand',
            field=models.CharField(blank=True, help_text='Card brand, e.g., Visa, Mastercard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='card_last4',
            field=models.CharField(blank=True, help_text='The last 4 digits of the card number', max_length=4, null=True),
        ),
    ]
