# Generated by Django 4.2.13 on 2025-07-05 19:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_guest_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Surcharge applied to this specific transaction (e.g., card processing fee).', max_digits=10),
        ),
    ]
