# Generated by Django 4.2.13 on 2025-06-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymenttransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
