# Generated by Django 4.2.13 on 2025-07-09 07:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymenttransaction_surcharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='tip',
        ),
        migrations.AddField(
            model_name='payment',
            name='total_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The grand total collected, including amount paid, tips, and surcharges.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_surcharges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total surcharges collected across all transactions.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_tips',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total tips collected across all transactions for this payment.', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
