# Generated by Django 4.2.13 on 2025-06-17 05:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Reason for the refund.', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The amount of this transaction that has been refunded.', max_digits=10),
        ),
    ]
