# Generated by Django 4.2.13 on 2025-07-10 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_remove_payment_tip_payment_total_collected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique gift card code', max_length=20, unique=True)),
                ('original_balance', models.DecimalField(decimal_places=2, help_text='Original balance when the gift card was created', max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, help_text='Current remaining balance on the gift card', max_digits=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired'), ('REDEEMED', 'Fully Redeemed')], default='ACTIVE', help_text='Current status of the gift card', max_length=20)),
                ('issued_date', models.DateTimeField(auto_now_add=True, help_text='Date when the gift card was issued')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Optional expiry date for the gift card', null=True)),
                ('last_used_date', models.DateTimeField(blank=True, help_text='Last date when this gift card was used', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the gift card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='payments_gi_code_4a7e40_idx'), models.Index(fields=['status'], name='payments_gi_status_50728d_idx')],
            },
        ),
    ]
