# Generated by Django 4.2.13 on 2025-07-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_giftcard_created_at_alter_giftcard_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='The payment ID from the old system.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='The transaction ID from the old system.', null=True, unique=True),
        ),
    ]
