# Generated by Django 4.2.13 on 2025-08-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_payment_status_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_number'], name='payment_number_idx'),
        ),
    ]
