# Generated by Django 4.2.13 on 2025-08-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_payment_number_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at', 'payment_number'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
