# Generated by Django 4.2.13 on 2025-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_payment_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['current_balance'], name='payments_gi_current_ac5dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['expiry_date'], name='payments_gi_expiry__3f2ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['status', 'current_balance'], name='payments_gi_status_852f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment'], name='payments_pa_payment_0e8e31_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['method'], name='payments_pa_method_4a8dce_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status'], name='payments_pa_status_b6726a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['transaction_id'], name='payments_pa_transac_c1fd68_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['created_at'], name='payments_pa_created_a246c6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['payment', 'status'], name='payments_pa_payment_b2e36e_idx'),
        ),
    ]
