# Generated by Django 4.2.13 on 2025-08-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_giftcard_payments_gi_current_ac5dfc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD_TERMINAL', 'Card Terminal'), ('CARD_ONLINE', 'Card Online'), ('GIFT_CARD', 'Gift Card'), ('DOORDASH', 'DoorDash'), ('UBER_EATS', 'Uber Eats')], max_length=20),
        ),
    ]
