# Generated by Django 4.2.13 on 2025-10-02 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('payments', '0013_alter_paymenttransaction_method'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='giftcard',
            name='payments_gi_code_4a7e40_idx',
        ),
        migrations.RemoveIndex(
            model_name='giftcard',
            name='payments_gi_status_50728d_idx',
        ),
        migrations.RemoveIndex(
            model_name='giftcard',
            name='payments_gi_current_ac5dfc_idx',
        ),
        migrations.RemoveIndex(
            model_name='giftcard',
            name='payments_gi_expiry__3f2ffa_idx',
        ),
        migrations.RemoveIndex(
            model_name='giftcard',
            name='payments_gi_status_852f1a_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_order_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_created_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_order_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_payment_0e8e31_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_method_4a8dce_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_status_b6726a_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_transac_c1fd68_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_created_a246c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payments_pa_payment_b2e36e_idx',
        ),
        migrations.AddField(
            model_name='giftcard',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant.tenant'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique gift card code', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['tenant', 'code'], name='payments_gi_tenant__2cd925_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['tenant', 'status'], name='payments_gi_tenant__bb7ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['tenant', 'current_balance'], name='payments_gi_tenant__6f40e0_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['tenant', 'expiry_date'], name='payments_gi_tenant__d33d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['tenant', 'status', 'current_balance'], name='payments_gi_tenant__b70035_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'status'], name='payment_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'order', 'status'], name='payment_ten_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'created_at'], name='payment_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_number'], name='payment_tenant_number_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'payment'], name='payments_pa_tenant__94cb68_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'method'], name='payments_pa_tenant__3241fc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'status'], name='payments_pa_tenant__5f54b1_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'transaction_id'], name='payments_pa_tenant__e7717a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'created_at'], name='payments_pa_tenant__2dd175_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['tenant', 'payment', 'status'], name='payments_pa_tenant__b5f30e_idx'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_gift_card_code_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_number__isnull', False)), fields=('tenant', 'payment_number'), name='unique_payment_number_per_tenant'),
        ),
    ]
