# Generated by Django 4.2.13 on 2025-10-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_fix_remaining_null_tenants'),  # Wait for data migration
        ('payments', '0014_remove_giftcard_payments_gi_code_4a7e40_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_cards', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='tenant.tenant'),
        ),
    ]
