# Generated by Django 4.2.13 on 2025-10-30 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0030_remove_kitchenzone_auto_print_and_more'),
        ('payments', '0016_add_store_location_with_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='allocation_policy_snapshot',
            field=models.JSONField(blank=True, help_text='Policy snapshot for deterministic refund allocation. Stores: tip_base (SUBTOTAL/SUBTOTAL_PLUS_TAX), surcharge_base, surcharge_applies_to_tip, rounding method, currency.', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='store_location',
            field=models.ForeignKey(blank=True, help_text='Denormalized from Order for fast location-based queries', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='settings.storelocation'),
        ),
    ]
