# Generated by Django 4.2.13 on 2025-10-12 23:35

from django.db import migrations, models
import uuid


def generate_uuids(apps, schema_editor):
    """Generate UUIDs for all existing TerminalRegistration records."""
    TerminalRegistration = apps.get_model('terminals', 'TerminalRegistration')
    for terminal in TerminalRegistration.objects.all():
        terminal.id = uuid.uuid4()
        terminal.save(update_fields=['id'])


def migrate_m2m_table(apps, schema_editor):
    """
    Migrate the many-to-many table to use UUIDs instead of device_id.
    Maps old device_id (VARCHAR) to new id (UUID).
    """
    # This is done via raw SQL because we need to update the junction table
    # which doesn't have a Django model
    schema_editor.execute("""
        -- Step 1: Add temporary UUID column
        ALTER TABLE settings_webordersettings_web_receipt_terminals
        ADD COLUMN terminalregistration_id_new UUID;

        -- Step 2: Map old device_id to new UUID id
        UPDATE settings_webordersettings_web_receipt_terminals AS m2m
        SET terminalregistration_id_new = tr.id
        FROM settings_terminalregistration AS tr
        WHERE m2m.terminalregistration_id = tr.device_id;

        -- Step 3: Drop old column
        ALTER TABLE settings_webordersettings_web_receipt_terminals
        DROP COLUMN terminalregistration_id;

        -- Step 4: Rename new column to old name
        ALTER TABLE settings_webordersettings_web_receipt_terminals
        RENAME COLUMN terminalregistration_id_new TO terminalregistration_id;
    """)


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0002_add_missing_fks'),
        ('settings', '0009_add_web_order_settings'),  # Need this to modify FK
    ]

    operations = [
        # Step 1: Add id field as nullable UUID (not primary key yet)
        migrations.AddField(
            model_name='terminalregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),

        # Step 2: Generate UUIDs for all existing rows
        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop),

        # Step 3: Make id non-nullable and unique (but not primary key yet)
        migrations.AlterField(
            model_name='terminalregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),

        # Step 4: Drop the foreign key from WebOrderSettings to TerminalRegistration
        migrations.RunSQL(
            sql='ALTER TABLE settings_webordersettings_web_receipt_terminals DROP CONSTRAINT IF EXISTS settings_weborderset_terminalregistration_0abd6ded_fk_settings_;',
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Step 5: Migrate the many-to-many table to use UUIDs
        migrations.RunPython(migrate_m2m_table, reverse_code=migrations.RunPython.noop),

        # Step 6: Remove primary key constraint from device_id and make it a regular field
        migrations.AlterField(
            model_name='terminalregistration',
            name='device_id',
            field=models.CharField(max_length=255),
        ),

        # Step 7: Set id as the new primary key
        migrations.AlterField(
            model_name='terminalregistration',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),

        # Step 8: Recreate the foreign key pointing to the new UUID id field
        migrations.RunSQL(
            sql='''
                ALTER TABLE settings_webordersettings_web_receipt_terminals
                ADD CONSTRAINT settings_weborderset_terminalregistration_0abd6ded_fk_settings_
                FOREIGN KEY (terminalregistration_id)
                REFERENCES settings_terminalregistration(id)
                DEFERRABLE INITIALLY DEFERRED;
            ''',
            reverse_sql='ALTER TABLE settings_webordersettings_web_receipt_terminals DROP CONSTRAINT IF EXISTS settings_weborderset_terminalregistration_0abd6ded_fk_settings_;',
        ),
    ]
