# Generated by Django 4.2.13 on 2025-11-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0003_terminalregistration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalregistration',
            name='offline_capture_window_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours before offline transactions must be captured'),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='offline_daily_limit',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Maximum total offline transactions per day', max_digits=10),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='offline_enabled',
            field=models.BooleanField(default=False, help_text='Enable offline card payments for this terminal'),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='offline_transaction_count_limit',
            field=models.PositiveIntegerField(default=20, help_text='Maximum number of offline transactions per day'),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='offline_transaction_limit',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Maximum amount per offline transaction', max_digits=10),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='signing_secret',
            field=models.CharField(blank=True, help_text='HMAC secret for verifying offline payloads (TODO: Encrypt at rest in Phase 2)', max_length=255),
        ),
    ]
