# Generated by Django 4.2.13 on 2025-12-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0004_terminalregistration_offline_capture_window_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalregistration',
            name='exposure_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current offline exposure (total pending transaction value)', max_digits=10),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='last_flush_success_at',
            field=models.DateTimeField(blank=True, help_text='Last successful queue flush to backend', null=True),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat received from terminal', null=True),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='last_sync_success_at',
            field=models.DateTimeField(blank=True, help_text='Last successful full sync to backend', null=True),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='offline_since',
            field=models.DateTimeField(blank=True, help_text='When terminal went offline (null if online)', null=True),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='pending_operations_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of operations pending sync at last heartbeat'),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='pending_orders_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of orders pending sync at last heartbeat'),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='sync_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('online', 'Online'), ('offline', 'Offline'), ('syncing', 'Syncing'), ('error', 'Error')], default='unknown', help_text='Current sync state of the terminal (unknown until first heartbeat)', max_length=20),
        ),
    ]
