# Generated by Django 4.2.13 on 2025-12-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0005_terminalregistration_exposure_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalregistration',
            name='daily_offline_order_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of offline orders synced today (resets at midnight)'),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='daily_offline_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cumulative offline order revenue today (resets at midnight)', max_digits=10),
        ),
        migrations.AddField(
            model_name='terminalregistration',
            name='daily_offline_revenue_reset_at',
            field=models.DateTimeField(blank=True, help_text='When daily offline metrics were last reset', null=True),
        ),
        migrations.AlterField(
            model_name='terminalregistration',
            name='exposure_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Current offline card exposure (pending capture value)', max_digits=10),
        ),
    ]
