# Generated by Django 4.2.13 on 2025-12-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0006_terminalregistration_daily_offline_order_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalregistration',
            name='parked_at',
            field=models.DateTimeField(blank=True, help_text='When terminal was intentionally parked/shutdown. Cleared on next heartbeat.', null=True),
        ),
    ]
