# Generated by Django 4.2.13 on 2025-12-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminals', '0007_add_parked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminalregistration',
            name='offline_alert_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the offline alert email was sent. Reset on heartbeat.', null=True),
        ),
    ]
