# Generated by Django 4.2.13 on 2025-12-10

from django.db import migrations


class Migration(migrations.Migration):
    """
    Remove offline spending limit fields.

    These limits were never enforced in production - the check code was
    broken and other POS systems (Square, Toast) don't have offline limits.
    Stripe's offline mode also doesn't enforce limits.

    Keeping: offline_enabled, offline_capture_window_hours, signing_secret
    (for authentication), exposure_amount (for ops visibility).
    """

    dependencies = [
        ('terminals', '0008_add_offline_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminalregistration',
            name='offline_transaction_limit',
        ),
        migrations.RemoveField(
            model_name='terminalregistration',
            name='offline_daily_limit',
        ),
        migrations.RemoveField(
            model_name='terminalregistration',
            name='offline_transaction_count_limit',
        ),
    ]
