# Generated by Django 4.2.13 on 2025-06-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='min_purchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The minimum subtotal required for the discount to apply.', max_digits=10, null=True),
        ),
    ]
