# Generated by Django 4.2.13 on 2025-07-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, help_text='Optional code for manual discounts', max_length=50, null=True, unique=True),
        ),
    ]
