# Generated by Django 4.2.13 on 2025-08-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discount_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='discounts_d_is_acti_d60cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['type', 'scope'], name='discounts_d_type_611057_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['code'], name='discounts_d_code_3a970a_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['is_active', 'type'], name='discounts_d_is_acti_9556b4_idx'),
        ),
    ]
