# Generated by Django 4.2.13 on 2025-06-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_discount_min_purchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='buy_quantity',
            field=models.PositiveIntegerField(blank=True, help_text="For 'Buy X Get Y' discounts, the quantity of items the customer must buy (X).", null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='get_quantity',
            field=models.PositiveIntegerField(blank=True, help_text="For 'Buy X Get Y' discounts, the quantity of items the customer gets for free (Y).", null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED_AMOUNT', 'Fixed Amount'), ('BUY_X_GET_Y', 'Buy X Get Y')], max_length=20),
        ),
    ]
