# Generated by Django 4.2.13 on 2025-08-23 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discounts', '0003_discount_discounts_d_is_acti_d60cd2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this record was archived.', null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='User who archived this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Designates whether this record is active. Inactive records are considered archived/soft-deleted.'),
        ),
    ]
