# Generated by Django 4.2.13 on 2025-10-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('discounts', '0004_discount_archived_at_discount_archived_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discount',
            name='discounts_d_is_acti_d60cd2_idx',
        ),
        migrations.RemoveIndex(
            model_name='discount',
            name='discounts_d_type_611057_idx',
        ),
        migrations.RemoveIndex(
            model_name='discount',
            name='discounts_d_code_3a970a_idx',
        ),
        migrations.RemoveIndex(
            model_name='discount',
            name='discounts_d_is_acti_9556b4_idx',
        ),
        migrations.AddField(
            model_name='discount',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='code',
            field=models.CharField(blank=True, help_text='Optional code for manual discounts (unique per tenant)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['tenant', 'is_active', 'start_date', 'end_date'], name='discounts_d_tenant__63e2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['tenant', 'type', 'scope'], name='discounts_d_tenant__aae32a_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['tenant', 'code'], name='discounts_d_tenant__e56087_idx'),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['tenant', 'is_active', 'type'], name='discounts_d_tenant__4ec17d_idx'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_discount_name_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='discount',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('tenant', 'code'), name='unique_discount_code_per_tenant'),
        ),
    ]
