# Generated by Django 4.2.13 on 2025-10-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_fix_remaining_null_tenants'),  # Wait for data migration
        ('discounts', '0005_remove_discount_discounts_d_is_acti_d60cd2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='tenant.tenant'),
        ),
    ]
