# Generated by Django 4.2.13 on 2025-11-20 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_alter_discount_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
