# Generated by Django 4.2.13 on 2025-06-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for programmatic access (e.g., sync service)', max_length=64, null=True, unique=True, verbose_name='API key'),
        ),
    ]
