# Generated by Django 4.2.13 on 2025-08-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_users_user_usernam_65d164_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of API key for secure storage', max_length=64, null=True, unique=True, verbose_name='API key hash'),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, help_text='DEPRECATED: API key for programmatic access (use api_key_hash)', max_length=64, null=True, unique=True, verbose_name='API key'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['api_key_hash'], name='users_user_api_key_954b24_idx'),
        ),
    ]
