# Generated by Django 4.2.13 on 2025-08-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_api_key_hash_alter_user_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_api_key_360026_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_api_key_954b24_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='api_key_hash',
        ),
    ]
