# Generated by Django 4.2.13 on 2025-09-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier')], default='CASHIER', max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='A unique username for POS login.', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
