# Generated by Django 4.2.13 on 2025-10-02 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('users', '0012_alter_user_role_alter_user_username'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_role_feee3d_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_is_acti_a8c04a_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_6f2530_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_usernam_65d164_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='The tenant this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenant.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='A unique username for POS login (unique per tenant).', max_length=150, null=True, verbose_name='username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'email'], name='users_user_tenant__4b6564_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'role', 'is_pos_staff'], name='users_user_tenant__5bf05c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'is_active', 'role'], name='users_user_tenant__c7473a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['tenant', 'username'], name='users_user_tenant__bb9518_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='unique_user_email_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('username__isnull', False)), fields=('tenant', 'username'), name='unique_user_username_per_tenant'),
        ),
    ]
