# Generated by Django 4.2.13 on 2025-10-02 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0003_fix_remaining_null_tenants'),  # Wait for data migration
        ('users', '0013_remove_user_users_user_role_feee3d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(help_text='The tenant this user belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenant.tenant'),
        ),
    ]
